### ISSUE TITLE
Diablo III does not save

### ISSUE THREAD

**Issue by namescmyta** [xenia-project/game-compatibility#1114]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Diablo-III/66acd000-77fe-1000-9115-d802394f07d1)

Tested on https://github.com/xenia-project/xenia/commit/21def8a5223624bb05c78a4a9a633976170df0ef

# Issues:
Autosave icon doesn't even spinning while in-game, and on checkpoints where it should spin and save your profile. I can press Back to start screen from character screen, then press start again, and game asking me to do "fresh start" settings again, so user profile (where game misc settings and characters is stored) isn't even creating/loading/saving.

**Comment by gibbed** [comment]
Please follow the instructions when creating a new game compatibility issue.

**Comment by namescmyta** [comment]
Come on, I followed it. I wrote game id, and commit, why close?

**Comment by namescmyta** [comment]
I don't know how to use this thing correctly, sorry. I'm first time here.

**Comment by namescmyta** [comment]
I don't even know english very well, i'm russian. Please, look at the issue

**Comment by gibbed** [comment]
You did include the game ID and commit, but we expect certain formatting of the issue title and text, which you didn't follow the instructions for.

**Comment by namescmyta** [comment]
> You did include the game ID and commit, but we expect certain formatting of the issue title and text, which you didn't follow the instructions for.
Sorry I'm newb, I tried to understand but it's too difficult for me

**Comment by gibbed** [comment]
I've gone ahead and fixed the formatting of the issue, please use this as an example for the future.

**Comment by namescmyta** [comment]
Big thanks for mercy, sir! God bless you and emulator.

**Comment by Wanderer189** [comment]
I would love to see support for more than one controller to test with this game

**Comment by LeyBasilio** [comment]
Sound is fixed in the 394F07D4, not tested with the 394F07D1. Thanks!

**Comment by Juntal** [comment]
Has a problem when the second player enters the game, I'm not sure if it is related to AutoSave.

**Comment by Wanderer189** [comment]
I don't think Xenia supports more than one controller yet. That is what I am hoping will get implemented here, giving feedback...

**Comment by LeyBasilio** [comment]
Tested here n maybe the emulator auto detect a second controller, cause when u plug a second one, the "Press A button" appears. But yeah, the crash appears to be related to autosave bug.

**Comment by Wanderer189** [comment]
When I press A on a 2nd controller, I just get the swirly thinking thing at the top right like the game is trying, but it hangs there forever. I figured the game is waiting for a hand-shake or something, but Xenia doesn't know how to respond???

**Comment by LeyBasilio** [comment]
> When I press A on a 2nd controller, I just get the swirly thinking thing at the top right like the game is trying, but it hangs there forever. I figured the game is waiting for a hand-shake or something, but Xenia doesn't know how to respond???

Yep, i think when they fix the autosave will work fine the 2nd controller.

**Comment by Pik-a-boo** [comment]
Is this also for the ultimate edition?

**Comment by LeyBasilio** [comment]
> Is this also for the ultimate edition?

Yep, same.

**Comment by pow4me123** [comment]
i hope they fix the auto save.. but it's been longtime and still nothing..

**Comment by rastamaan** [comment]
To solve save problem create "394F07D4" folder in save folder then create "00000001" inside and create another one inside called "D3.SAV" and then create "HEROES" folder inside ;) and save working :)

**Comment by rastamaan** [comment]
Sorry for my English :)

**Comment by rastamaan** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/52463375/60529324-a70c4d80-9cf6-11e9-91f9-89a3ecf638bf.png)

**Comment by pow4me123** [comment]
> To solve save problem create "394F07D4" folder in save folder then create "00000001" inside and create another one inside called "D3.SAV" and then create "HEROES" folder inside ;) and save working :)

OMG brooo finally!! it workinggg!! thank youuuuuuuuuuuuuuuu!!

**Comment by Juntal** [comment]
> To solve save problem create "394F07D4" folder in save folder then create "00000001" inside and create another one inside called "D3.SAV" and then create "HEROES" folder inside ;) and save working :)

Works singleplayer but no for two players...

**Comment by ThePapaw** [comment]
As I see these files have to be created and were missing, it is still not saving for me. I assume it should save something after character creation and a checkpoint. I am getting nothing? I am running the DX12 version, Vulcun version isn't displaying correctly on my 8086k with 1080ti

**Comment by LeyBasilio** [comment]
> To solve save problem create "394F07D4" folder in save folder then create "00000001" inside and create another one inside called "D3.SAV" and then create "HEROES" folder inside ;) and save working :)

Thanks a lot! Finaly! <3

**Comment by BiatuAutMiahn** [comment]
Can you guys check if Xenia is trying to create a file instead of a directory? or nothing at all?

**Comment by ThePapaw** [comment]
I went to the "content" folder and added the following folders: 394F07D4 (is the game ID showing in Xenia)  > 00000001 > D3.SAV > HEROES (tried it without the heros directory as well), then ran game, played until a couple checkpoints and nothing was ever saved in any of the new directories I created, I watched them as I played. Hope this helps

**Comment by rastamaan** [comment]
> I went to the "content" folder and added the following folders: 394F07D4 (is the game ID showing in Xenia) > 00000001 > D3.SAV > HEROES (tried it without the heros directory as well), then ran game, played until a couple checkpoints and nothing was ever saved in any of the new directories I created, I watched them as I played. Hope this helps

Check Your Diablo version :) And if you have another that "394F07D4" change this folder name to your version :) 
![Bez tytułu](https://user-images.githubusercontent.com/52463375/60614729-c88c3880-9dcd-11e9-9c9c-58f57d2218a4.png)
There is diablo version

**Comment by rastamaan** [comment]
Check content>profile folder and open "FFFE07D1" file with notepad and check that is there Diablo? I have it there. Maybe there is a problem?

**Comment by rastamaan** [comment]
And create "portable.txt" in main folder that you have xenia.exe if you dont have it.

**Comment by ThePapaw** [comment]
I am running the same 394F07D4 version, like I said above. I do NOT have a "profile" folder within the content folder, is that part of my problem

**Comment by ThePapaw** [comment]
I added the profile folder, it is adding content there now, also added portable.txt file, let me check things real quick

**Comment by ThePapaw** [comment]
yep, it is saving now, that you rasamann, so does the vulcan version work for anyone?

**Comment by fragmajster** [comment]
This trick is not working for me on Win10 1902, I have DX12 build from 25th May downloaded from Xenia web page, from what I see @rastamaan  has newer version from 29th June :(

I tried setting path like this:
![Zrzut ekranu (30)](https://user-images.githubusercontent.com/52698944/60876887-0d382980-a23d-11e9-8ae4-dadca41697de.png)

And also like this:
![Zrzut ekranu (31)](https://user-images.githubusercontent.com/52698944/60876965-31940600-a23d-11e9-99ed-e921deab0736.png)

In both cases game is not saving, even tried running the emulator via Admin privilages, other games are saving correctly

**Comment by fragmajster** [comment]
NVM i fixed the issue with newer DX12 build (custom) one, let this be a indicator to others ;)

**Comment by Juntal** [comment]
Can someone help me with the second control?

**Comment by marcosdls** [comment]
-Using fix savegame- -Attempt to play with 2 controllers-
If you start the game using controller 2, the game is locked in the main menu.
![CapturaD3ROS-1](https://user-images.githubusercontent.com/29433517/60901997-4c6a7880-a245-11e9-925d-9d72b2b14a46.PNG)

If you start the game using controller 1, and then press "A" button  to "join the group" using controller 2, the save / loaded function appears loading infinitely.
![CapturaD3ROS-2](https://user-images.githubusercontent.com/29433517/60902120-7d4aad80-a245-11e9-883e-f6679cfad7d1.PNG)

Maybe the problem is that, playing with 2 controls,  Diablo 3 needs 2 Profiles to save / load. So, when trying to use the second profile - which does not exist - the game remains infinitely loaded.

**Comment by alefdedeus** [comment]
I did all these steps and the game still does not save :( I use windows 10 1093

> > I went to the "content" folder and added the following folders: 394F07D4 (is the game ID showing in Xenia) > 00000001 > D3.SAV > HEROES (tried it without the heros directory as well), then ran game, played until a couple checkpoints and nothing was ever saved in any of the new directories I created, I watched them as I played. Hope this helps
> 
> Check Your Diablo version :) And if you have another that "394F07D4" change this folder name to your version :)
> ![Bez tytułu](https://user-images.githubusercontent.com/52463375/60614729-c88c3880-9dcd-11e9-9c9c-58f57d2218a4.png)
> There is diablo version

**Comment by alefdedeus** [comment]
> yep, it is saving now, thank you rasamann, so does the vulcan version work for anyone?

What version of windows?

**Comment by illusion98** [comment]
Playable https://youtu.be/0jJ2cnkudgc
See this comment for workaround https://github.com/xenia-project/game-compatibility/issues/1114#issuecomment-507748585

**Comment by gandalfthewhite19890404** [comment]
Game has input issues - looks like buttons are pressed multiply times, I am using xinput, with x360ce. Also sound is glitchy.

**Comment by Kyuflow** [comment]
how do you solve infinite loop error co op? I really want to play with friends co op !!!!

**Comment by donrogoo** [comment]
hi i have tried to open diablo3 i have windows 7 8giga ram i5 processor
and this always happens can you please find a solution

![diabloo](https://user-images.githubusercontent.com/57328996/68090950-9e817a80-fe82-11e9-9485-bafbd4d51116.JPG)

**Comment by donrogoo** [comment]
and gigabyte nvidia geforce gt 1030

**Comment by donrogoo** [comment]
why did u delete my comment

**Comment by Margen67** [comment]
@donrogoo Tech support doesn't belong on game-compatibility. Go to the [Discord server](https://discord.gg/5g93S8H) for that.

**Comment by gandalfthewhite19890404** [comment]
Remove, please, its different game - https://github.com/xenia-project/game-compatibility/issues/1114#issuecomment-509696092

**Comment by dinosmike** [comment]
Xenia Diablo 3 saves did not work, but this helped me https://github.com/xenia-project/game-compatibility/issues/1114#issuecomment-507748585 and now saves work properly. it looks like this http://joxi.ru/BA0RkQKSMKk0jm

It is unfortunate that **two players cannot be played**, after connecting the second player an endless loading appears.

**Comment by Kyuflow** [comment]
Does Local Multiplayer work?

**Comment by gabrielarantest** [comment]
The save solution does no work for me. I also cannot play with two controllers.

**Comment by gandalfthewhite19890404** [comment]
Latest master - game is crashing after you're press START in main menu.
I gonna find regressed build and update this post.

**Comment by Ripper00420** [comment]
using latest master and the folders and files are there. it still crashes after you hit start after exiting the game

**Comment by gandalfthewhite19890404** [comment]
@Ripper00420 Hey, do not confuse people, 394F07D1 is Reaper of Souls folder. So your comment is not related with this thread.
Diablo III works without issues on latest master, with working saves.

**Comment by SnaxxNZ** [comment]
Game is loading in Spanish and seem to be ignoring the user_country/user_language settings in "xenia.config".

**Comment by Ripper00420** [comment]
> 

394F07D4 is my ROS and the saves are working now, but 2 player is not with the latest buid.

**Comment by baskax** [comment]
@Ripper00420 try using canary

**Comment by chelonavek** [comment]
Yeah, endless loading for second player on Xenia Master. Two player mode works well on Xenia Canary!!! Thank you, @baskax :fire:

> Xenia Diablo 3 saves did not work, but this helped me [#1114 (comment)](https://github.com/xenia-project/game-compatibility/issues/1114#issuecomment-507748585) and now saves work properly. it looks like this http://joxi.ru/BA0RkQKSMKk0jm
> 
> It is unfortunate that **two players cannot be played**, after connecting the second player an endless loading appears.

> @Ripper00420 try using canary


![image](https://github.com/xenia-project/game-compatibility/assets/153221362/2697e82c-a4b8-42e1-a772-7ccd126bc31c)
