### ISSUE TITLE
D8024D53 - Gears of War 2

### ISSUE THREAD

**Issue by agrecalypse** [xenia-project/game-compatibility#163]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Gears-of-War-2/66acd000-77fe-1000-9115-d8024d53082d)

https://github.com/benvanik/xenia/commit/256a4c402cf4852af24b8aec164af5449a57bf10

**State-Load** **State-Crash**

* Loads past initial Epic Games screen & crashes immediately after Microsoft Game Studios screen

[Log](https://gist.github.com/agrecalypse/2971b764d3841a28915f/raw/4f051d14e2a9fe6af99d8b61ab9c39b682f9dbe2/GearsofWar2_r_e_21_28.log)

**Comment by theoldsport** [comment]
Main menu now renders 3D. The game freezes immediately afterward

[OpenGL]
![gears of war 2](https://cloud.githubusercontent.com/assets/13494133/16213832/4e2ac7ee-3707-11e6-9592-9f79d9198f78.png)

**Comment by SirHayek** [comment]
any progress? pls need to play xD

**Comment by TGLTClutch** [comment]
Getting AVX CPU later, then I can use Xenia otherwise. I will have to look on YouTube but no one tests gears of war anymore.

**Comment by stride21** [comment]
plays intro videos and then has a black screen with main menu music playing but unable to do anything while on it.
![capture](https://user-images.githubusercontent.com/37915864/43047683-a450251e-8da0-11e8-9fc7-2f74f827ed6c.JPG)
Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2217180/xenia.zip)

**Comment by CeckoGT** [comment]
Hello people pleas send the link game adres Gears Of War 2

**Comment by forcecde** [comment]
![image](https://user-images.githubusercontent.com/29419296/52915761-a9758a00-32b6-11e9-8450-1edd0afade3b.png)
Continue Black screen

**Comment by TGLTClutch** [comment]
@forcecde 
Please include your logs as well as which build you used.

**Comment by von-maurus** [comment]
So can it run in Vulkan or Direct12?. Also I have a RTX 2060 GPU

**Comment by win98and95** [comment]
Not yet because UnrealEngine games uses an [extended memory range](https://github.com/xenia-project/xenia/blob/master/docs/cpu.md#memory) that's not available in Xenia yet.
`0xE0000000 - 0xFFFFFFFF`

**Comment by InwardHydra** [comment]
> Hello people pleas send the link game adres Gears Of War 2

Sorry, but we cannot send you a link, as we don't promote piracy. If you want Gears 2, you will need a modded 360.

**Comment by win98and95** [comment]
the titleID for this issue is incorrect.
it should be `4D53082D`

**Comment by CyrusDF98** [comment]
I have the same problem, has there been progress?

**Comment by Gliniak** [comment]
Tested on: https://github.com/xenia-project/xenia/commit/39490f3c3a79e9c2e1acad37609108b4c14bd459

### Overview:
Quite playable, saving works. Every n-th frame there is a bump of frametime to around 150ms

### Log:
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/4896330/xenia.zip)

### Screenshots:
![image](https://user-images.githubusercontent.com/153369/87032910-9c2ba900-c1e5-11ea-8586-f9c84978b44f.png)
![image](https://user-images.githubusercontent.com/153369/87032974-b5ccf080-c1e5-11ea-9cd6-fc121fd9f9f7.png)
![image](https://user-images.githubusercontent.com/153369/87033055-d432ec00-c1e5-11ea-801a-178a1854c41b.png)

**Comment by kunit1** [comment]
Is the cause for the graphical corruption on the faces know?

**Comment by AlexByte** [comment]
@kunit1 the cause is emulator optimization.

**Comment by fraj999** [comment]
how can i download the game

**Comment by AlexByte** [comment]
@fraj999 https://github.com/xenia-project/xenia/wiki/Quickstart#how-to-rip-games

**Comment by lokeshsharmaj** [comment]
Finished the game. It's clearly playable but only issue is black shadows which can come anywhere. Finished it without any crash.

**Comment by tuxytux** [comment]
With the 28/04/2021 build, stuttering issues has been solved. With vsync off, i get an almost smooth 60fps. Also significant framrate boost. Before this build i was having 20-30 fps on a 
3060 Ti.
Whats left is the black texture issue on faces and sometimes in the world, depending on which chapter you are in. In some chapters it is barely noticeable. Can this be solved?

**Comment by MasterProcrastinator** [comment]
I'm just trying out this emulation since The Coalition refuse to put some resources on remastering GoW2, you said you can get 60fps on GoW2? I thought 360 games were tied to 30 and required in house work to change it because of how FPS is tied to physics and stuff

**Comment by Boubleg21** [comment]
controls for gears of war 2 on the emulator?

**Comment by GorkiYX4** [comment]
Everything is worked, but some water collusions is missimg or broken, and shadows are not displayed correctly on characters.
But game is finished,  i have maybe 4 or 5 crashes, fps stable on 30.
![Desktop Screenshot 2022 05 21 - 16 48 36 24](https://user-images.githubusercontent.com/105969487/169644724-59980b83-1c1e-471f-bcdb-2ffe2dcc7322.png)
![Desktop Screenshot 2022 05 21 - 16 48 57 66](https://user-images.githubusercontent.com/105969487/169644729-c25cd0e0-c8d2-4a20-a32e-902e064d874a.png)
![Desktop Screenshot 2022 05 21 - 16 59 29 32](https://user-images.githubusercontent.com/105969487/169644731-7b3c9b5f-72cf-4c8e-a263-20f497efe64a.png)
![Desktop Screenshot 2022 05 21 - 14 38 50 99](https://user-images.githubusercontent.com/105969487/169644732-18302ac6-e8af-4b13-a08b-a32b9b6574a8.png)
![Desktop Screenshot 2022 05 21 - 15 15 58 70](https://user-images.githubusercontent.com/105969487/169644733-0b4640ab-15a5-4667-bec3-6f46a9e2cd27.png)
![Desktop Screenshot 2022 05 21 - 15 16 35 21](https://user-images.githubusercontent.com/105969487/169644734-dfb1a828-1ecb-48f6-af4f-a0be808668c6.png)

**Comment by dante3732** [comment]
There are places in these game where the game crashes constantly, but it also crashes randomly. Driver give TDR error.
It happened beginning with jun 23 2020 build and still not fixed.
There are no crashes on previous builds.
Windows 11 Pro x64 21H2
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 22.5.1
2x8 Gb DDR4 3200

**Comment by bomabomaboma** [comment]
[https://github.com/xenia-project/xenia/commit/37579d3bf0cd18633f8342a3c1e2d6b41fd3ed83](url) fixed rendering of all simulated fluid surfaces in Unreal Engine 3 titles (vertex animations w/ tessellated grids vs the cheaper translucencies used in most other UE3 games).

![image](https://user-images.githubusercontent.com/81534189/183476107-4da471b9-1812-4b3f-bf4f-e6c29b5411ce.png)
![image](https://user-images.githubusercontent.com/81534189/183477122-6a2aedde-16d9-42dd-a0a7-d14ea9ac427b.png)

**Comment by jfish871** [comment]
I am happy to report that I was able to play through the game from start to completion. The emulator only crashed 4 times due to it loosing the graphics device (some internal error on relating to the graphics pipeline). The only bug is that random polygons are solid black.

**Comment by wolfinston85** [comment]
Hey, managed to complete the game from start to finish without any serious issues, just some exploding Reavers near the end and  some screen tearing despite Vsync being enabled in the emu config in previous Canary versions, not present in the latest, more info in the video description. Uploaded some gameplay from one of the latest missions of the game. Thanks to the dev team as always.

[https://youtu.be/PTlnTTn16wo](url)

**Comment by arcues198750** [comment]
![image](https://github.com/xenia-project/game-compatibility/assets/98266884/371c2664-372e-4fc2-8f00-0c1397027f88)
Games shadow graphics look to be out of place/failing to render properly. Otherwise smooth frame rate.

**Comment by SloaJay** [comment]
> Games shadow graphics look to be out of place/failing to render properly. Otherwise smooth frame rate.
You can fix this shadowy issue somehow through patches in Xenia Canary. There is fix for this.

**Comment by Voidwalker57** [comment]
got a problem, when i start the game menu works fine however once I hit new game to start campaign my game is stuck on blackscreen. on steamdeck havent used vulken yet

**Comment by gagantous** [comment]
Hi, i tried to play this game on Linux based system (steamOS) and i got this glitch on all environment. 

I used GPU Vulkan instead of d3d12 because the game always freeze and hang the entire OS whenever someone shoot any kind of bullet. Here is some gameplay with that flash environment. 
https://youtu.be/EneZjItoWb0?si=oijI0Y5an0msmqX9

**Comment by dante3732** [comment]
> https://youtu.be/EneZjItoWb0?si=oijI0Y5an0msmqX9

It normal, vulkan not completed.

**Comment by gagantous** [comment]
> > https://youtu.be/EneZjItoWb0?si=oijI0Y5an0msmqX9
> 
> It normal, vulkan not completed.

I see, so what happen when i tried d3d12 version, it always freeze the entire system. When i tried on my laptop (Windows OS) its run pretty well without that flashy thing

**Comment by brianx87** [comment]
On SteamOS the game was directly loading into the gameplay and bypassing the cutscenes, loaded to black screen with only gunfire and character armour lights visible. Somehow I have managed to fix it by changing to vulkan and back to dx12, the only other thing I did was delete the game profile in xenia's content folder and disabled all the patches I had enabled as those where causing the game to freeze on load, then reenabled them. Somehow it works now, same can not be said for 3 and Judgement that have the same loading issue.

**Comment by SloaJay** [comment]
On **canary** ver _5ca173cd4_ with shadow fix from patches. And on ROV settings. Everything works fine. There is some issue with alpha effects. But they could be on real HW? Don't have original x-box to compare thou.
![somee effects](https://github.com/xenia-project/game-compatibility/assets/85364852/833b1532-f5bc-4a1c-998c-d0bed96ae718)

**Comment by YungYaboi** [comment]
> On SteamOS the game was directly loading into the gameplay and bypassing the cutscenes, loaded to black screen with only gunfire and character armour lights visible. Somehow I have managed to fix it by changing to vulkan and back to dx12, the only other thing I did was delete the game profile in xenia's content folder and disabled all the patches I had enabled as those where causing the game to freeze on load, then reenabled them. Somehow it works now, same can not be said for 3 and Judgement that have the same loading issue.

I'm having the same issue, but your fix didn't work. I'm using d3d12 on linux & the only thing that loads is the training grounds. Everything else gives "Error initializing network layer." For some reason, it still creates a save file after this error pops up while trying to begin a solo campaign. Launching that save file does load, but it has the exact issues you described of it not rendering the level with only gunfire and armour lights being visible.

The network error was closed 5 years ago without a fix, possibly due to that OP using Vulkan, but this issue happens when I try either Vulkan or d3d12.

I've tried deleting the shaders, the content folder for the game, with patches on & off, and with Vulkan as well as d3d12. Nothing worked.

**Comment by Leniptic** [comment]
> I'm having the same issue, but your fix didn't work. I'm using d3d12 on linux & the only thing that loads is the training grounds. Everything else gives "Error initializing network layer." For some reason, it still creates a save file after this error pops up while trying to begin a solo campaign. Launching that save file does load, but it has the exact issues you described of it not rendering the level with only gunfire and armour lights being visible.
> 
> The network error was closed 5 years ago without a fix, possibly due to that OP using Vulkan, but this issue happens when I try either Vulkan or d3d12.
> 
> I've tried deleting the shaders, the content folder for the game, with patches on & off, and with Vulkan as well as d3d12. Nothing worked.

Same issue. On Linux the game runs flawlessly in the training grounds, but I can't load into anywhere else. I always get "Error initializing network layer". Changing to Vulkan, D3D12 and messing with the license mask in the config didn't help.

**Comment by Leniptic** [comment]
> For anyone looking to get this working, I tried the fix for [Linux on Xenia netplay](https://github.com/AdrianCassar/xenia-canary/tree/netplay_canary_experimental_QoL?tab=readme-ov-file#linux-notes) and it worked. It removed the error message `Error initializing network layer.` which I suspect causing the black screen and only seeing bullet fire and armor lights.

Glad to know that fixes it, thanks for letting me know. Didn't have time to test it myself, so I was hoping someone else might give it a shot.

**Comment by Mcmunz** [comment]
> > > I'm having the same issue, but your fix didn't work. I'm using d3d12 on linux & the only thing that loads is the training grounds. Everything else gives "Error initializing network layer." For some reason, it still creates a save file after this error pops up while trying to begin a solo campaign. Launching that save file does load, but it has the exact issues you described of it not rendering the level with only gunfire and armour lights being visible.
> > > The network error was closed 5 years ago without a fix, possibly due to that OP using Vulkan, but this issue happens when I try either Vulkan or d3d12.
> > > I've tried deleting the shaders, the content folder for the game, with patches on & off, and with Vulkan as well as d3d12. Nothing worked.
> > 
> > 
> > Same issue. On Linux the game runs flawlessly in the training grounds, but I can't load into anywhere else. I always get "Error initializing network layer". Changing to Vulkan, D3D12 and messing with the license mask in the config didn't help.
> > Edit: I haven't tried this myself, but perhaps running Xenia Netplay and [using this section](https://github.com/AdrianCassar/xenia-canary/tree/netplay_canary_experimental_QoL?tab=readme-ov-file#linux-notes) would fix the issue
> 
> For anyone looking to get this working, I tried the fix for [Linux on Xenia netplay](https://github.com/AdrianCassar/xenia-canary/tree/netplay_canary_experimental_QoL?tab=readme-ov-file#linux-notes) and it worked. It removed the error message `Error initializing network layer.` which I suspect causing the black screen and only seeing bullet fire and armor lights.

Hi im trying to get this workinh on the Steam Deck
 Did this fix everything for you ?

**Comment by azaelbr** [comment]
![image](https://github.com/user-attachments/assets/eb1b9f41-d92f-494c-8162-a90a2fe2ad88)

Black Shading fix don't work for 2k or 4k resolution... I disabled Ambient Occlusion Too.
Someone have a new fix for this?

Rig
7800x3d
4070ti
32gb
Kingston Renegade

**Comment by databoose** [comment]
Getting `Error initializing network layer.` dialog before starting campaign, and i just spawn in a dark abyss with only gunfire, armor lighting and ingame UI showing.

Same issue as others have posted.

Running xenia on linux through wine, cannot confirm if xenia netplay works for this game as the netplay fork just crashes on startup for me.

**Comment by Leniptic** [comment]
> Getting `Error initializing network layer.` dialog before starting campaign, and i just spawn in a dark abyss with only gunfire, armor lighting and ingame UI showing.
> 
> Same issue as others have posted.
> 
> Running xenia on linux through wine, cannot confirm if xenia netplay works for this game as the netplay fork just crashes on startup for me.

Perhaps try the fix for failing to bind ports listed for Xenia Netplay regardless. I don't think they're Netplay-specific instructions, just that you should in theory only run into them when trying to play multiplayer/live games (but it seems Gears of War 2 is making some network call at boot). You can also try a different wine version. I've always had success with Bottles.

**Comment by Mcmunz** [comment]
> > Getting `Error initializing network layer.` dialog before starting campaign, and i just spawn in a dark abyss with only gunfire, armor lighting and ingame UI showing.
> > Same issue as others have posted.
> > Running xenia on linux through wine, cannot confirm if xenia netplay works for this game as the netplay fork just crashes on startup for me.
> 
> Perhaps try the fix for failing to bind ports listed for Xenia Netplay regardless. I don't think they're Netplay-specific instructions, just that you should in theory only run into them when trying to play multiplayer/live games (but it seems Gears of War 2 is making some network call at boot). You can also try a different wine version. I've always had success with Bottles.

Unfortunately the fix for Xenia Netplay does not resolve the issue. You can import a game save file from an external device and that will fix the black screen issue, however upon firing your weapon the game will crash and if youre playing on Steam Deck like me, it will completely hard crash your system.

**Comment by sonofnabe** [comment]
Had several different issues with the game. Running on SteamOS and netplay fix seems to work just fine. However, game crashes every single time my bullets hit either the glasses in the training segment of the story mode or when I hit enemies in the training ground gamemode. As a matter of fact, after trying it again, it seems to crash if I shoot anything too much. Thank you guys so much and if you can find anything please let me know.
[crash.zip](https://github.com/user-attachments/files/16777227/crash.zip)

**Comment by Margen67** [comment]
Xenia Canary issue: https://github.com/xenia-canary/game-compatibility/issues/46
