### ISSUE TITLE
4d5307d3 - Perfect Dark Zero

### ISSUE THREAD

**Issue by thesymbol** [xenia-project/game-compatibility#175]
http://marketplace.xbox.com/en-US/Product/Perfect-Dark-Zero/66acd000-77fe-1000-9115-d8024d5307d3

https://github.com/benvanik/xenia/commit/068b2056ca02a707b164693fefc9e0dd9637e6f2

https://gist.github.com/thesymbol/ccaa110d503c1d726a9a

* Crashes when trying to load first mission, music keeps playing for a while but then ends aswell.

![screenshot](https://cloud.githubusercontent.com/assets/541389/9828971/a3ca2b30-58f6-11e5-84b2-e486b5b245a7.png)

**Comment by Razzile** [comment]
state-menus?

**Comment by thesymbol** [comment]
Yes would be most appropriate.

**Comment by marlon99rocks** [comment]
plz make it work plz

**Comment by hubslave** [comment]
On xenia 1.0.1219-texsplit only one quarter of screen is rendered properly.
It looks really weird. Also font is really broken.
Btw: Want to play perfetttttttttttttttt zerrrrrrr?
![image](https://user-images.githubusercontent.com/29800872/37174026-a245d156-2315-11e8-8322-7da732c723eb.png)
Crashes after trying to load first mission, combat simulator shows only empty screen with no players and coes not launch
Log (i was watching the intro video, and then trying to launch first mission)
http://s000.tinyupload.com/index.php?file_id=01518967232239270073

**Comment by hubslave** [comment]
It actually does not crash on xenia from 3/4/18. It just hangs forever. Xenia can be controlled (F3 graph and setting time scalar still works), and takes about 20% from processor in taskmgr.

**Comment by Deathlock47** [comment]
Now crashes right when it starts showing the first intro video. It can be seen that the weird stretching bug is still present

![355](https://user-images.githubusercontent.com/22158671/40877262-59369a9a-6686-11e8-9f10-175d9767468a.png)

**Comment by tjd2** [comment]
## Tested on:
xenia-project/xenia@0d429fc
## Description
Only one quarter of screen is rendered properly (I am calling it Farlands effect: https://i.imgur.com/IVamj0N.png)
If you start any mission (with modified save) at any difficulty, game hangs after while. Music still plays for about 3 seconds and Xenia hangs forever and takes about 20% CPU load
If you start Combat Arena, set settings and advance to next screen (with list of players/bots), it's empty and game does not react to pressing start.
## Labels
state-menus
regression (previously there was no Farlands effect)
gpu-corrupt-drawing (in menus)
kernel-unimplemented-features
## Log
If you want, i can upload it.

**Comment by twrist** [comment]
Per attached log from Win98and95 in Discord, PDZ requires an Xbox Live state of sorts before it goes in-game. Recommending label `xam-live-signin-required`
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/2667428/xenia.zip)

**Comment by Qleses** [comment]
Please, make it possible, run perfectly perfect dark zero.I have hope that really someday runs ok.

**Comment by illusion98** [comment]
ingame https://github.com/xenia-project/xenia/commit/c43ccc073da10fcf2ba43c4f90746cbc9b26880d
![](https://cdn.discordapp.com/attachments/309008096800276490/652550896554737704/unknown.png)
![](https://cdn.discordapp.com/attachments/309008096800276490/652551649272922186/unknown.png)
Log: [xenia.zip](https://cdn.discordapp.com/attachments/459064743877935105/652553149587914772/xenia.zip)

**Comment by justinbacle** [comment]
Working, but random freeze in first level. 
Seems to be looping iver a compute shader 

`G> 00000004 Loaded tiled 1280x720x1 2D k_8_8_8_8 texture with 1 unpacked mip level, base at 0x1A8A0000 (size 3768320), mips at 0x00000000 (size 0)
G> 00000004 Resolve: (0,0)->(1216,640) of RT 0 (pitch 1280, 1 sample, format 0) at 720
G> 00000004 Resolve: Copying samples 0 to 0x1B520000 (1216x640, 2D), destination Z 0, destination format k_8_8_8_8, exponent bias 0, red and blue swapped
G> 00000004 Resolve: Copying using a compute shader
i> 0000006C VdSwap(BA83B420, 405BF110, BE710008, 454FFC00, BEEF0001, 454FFBC0(BA8A0000), 454FFBCC(00000006), 454FFBD0(00000000), 454FFBC8(00000500), 454FFBC4(000002D0))
i> 00000028 RtlNtStatusToDosError 103 => 3E5
i> 00000028 RtlNtStatusToDosError 103 => 3E5
!> 00000028 Unimplemented XLIVEBASE message app=000000FC, msg=0005800E, arg1=4018F1C0, arg2=4018F230
G> 00000004 Resolve: (0,0)->(1280,720) of RT 0 (pitch 1280, 1 sample, format 0) at 720
G> 00000004 Resolve: Copying samples 0 to 0x1A8A0000 (1280x720, 2D), destination Z 0, destination format k_8_8_8_8, exponent bias 0, red and blue swapped
G> 00000004 Resolve: Copying using a compute shader
i> 00000004 XE_SWAP`

Log is filling up very fast then and gets huge

**Comment by justinbacle** [comment]
Doesn't work anymore on latest release (2021 Feb 01) crashes instantly. Log follows 
```
i> 00000278 Build: detached / a6954aced397ea1846379dbb48571a76637dadce on Feb  1 2021
i> 00000278 Storage root: C:\Users\******\Documents\Xenia
w> 00000C44 SDL GameControllerDB: file 'gamecontrollerdb.txt' does not exist.
w> 00000278 Failed to load dxcompiler.dll, converted DXIL disassembly for debugging will be unavailable - if needed, download the DirectX Shader Compiler from https://github.com/microsoft/DirectXShaderCompiler/releases and place the DLL in the Xenia directory
w> F8000004 GPU: Write to unknown register (0004 = 00FEEFEE)
w> F8000004 GPU: Write to unknown register (0007 = F00DF00D)
w> F8000004 GPU: Write to unknown register (0081 = 00010000)
w> F8000004 GPU: Write to unknown register (1E4E = 00000000)
!> F8000028 ==== CRASH DUMP ====
!> F8000028 Thread ID (Host: 0x0000518C / Guest: 0x00000006)
!> F8000028 Thread Handle: 0xF8000028
!> F8000028 PC: 0x8272D350
!> F8000028 Registers:
!> F8000028  r0   = 0000000000000000
!> F8000028  r1   = 000000004018F970
!> F8000028  r2   = 0000000000000000
!> F8000028  r3   = 0000000000000000
!> F8000028  r4   = 0000000000000000
!> F8000028  r5   = 0000000000000008
!> F8000028  r6   = 000000003FEFFE54
!> F8000028  r7   = 000000003FEFF014
!> F8000028  r8   = 000000003FEFF008
!> F8000028  r9   = 00000000000000FF
!> F8000028  r10  = FFFFFFFFDEADBEEF
!> F8000028  r11  = 000000003FEFFE54
!> F8000028  r12  = 000000008272D33C
!> F8000028  r13  = 000000000003E000
!> F8000028  r14  = 0000000000000000
!> F8000028  r15  = 0000000000000000
!> F8000028  r16  = 0000000000000000
!> F8000028  r17  = 0000000000000000
!> F8000028  r18  = 0000000000000000
!> F8000028  r19  = 0000000000000000
!> F8000028  r20  = 0000000000000000
!> F8000028  r21  = 0000000000000000
!> F8000028  r22  = 0000000000000000
!> F8000028  r23  = FFFFFFFF82E40000
!> F8000028  r24  = FFFFFFFF82E40000
!> F8000028  r25  = 0000000000000E1C
!> F8000028  r26  = 0000000000000E1C
!> F8000028  r27  = 0000000000000000
!> F8000028  r28  = 0000000000000000
!> F8000028  r29  = 000000003FEFF030
!> F8000028  r30  = 0000000040300138
!> F8000028  r31  = 0000000040300138
!> F8000028  f0   = 0000000000000E1C = (double)1.7846e-320 = (float)5.061e-42
!> F8000028  f1   = 3FC5C28F60000000 = (double)0.17000000178813934 = (float)3.689349e+19
!> F8000028  f2   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f3   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f4   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f5   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f6   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f7   = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f8   = 3F67B31E27060394 = (double)0.0028930272021061108 = (float)1.8598175e-15
!> F8000028  f9   = BF6F871C52A89610 = (double)-0.003848605459341632 = (float)362036070000.0
!> F8000028  f10  = 400A800000000000 = (double)3.3125 = (float)0.0
!> F8000028  f11  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f12  = 40AC360000000000 = (double)3611.0 = (float)0.0
!> F8000028  f13  = 3FF0000000000000 = (double)1.0 = (float)0.0
!> F8000028  f14  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f15  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f16  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f17  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f18  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f19  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f20  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f21  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f22  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f23  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f24  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f25  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f26  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f27  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f28  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f29  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f30  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  f31  = 0000000000000000 = (double)0.0 = (float)0.0
!> F8000028  v0   = [0x00000000, 0xBFA00000, 0x00000000, 0x00000000]
!> F8000028  v1   = [0x40000000, 0xFFC00000, 0xFFC00000, 0xFFC00000]
!> F8000028  v2   = [0x3F06E7D4, 0xFFC00000, 0xFFC00000, 0xFFC00000]
!> F8000028  v3   = [0x7FC00000, 0x7FC00000, 0x7FC00000, 0x7FC00000]
!> F8000028  v4   = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v5   = [0x00000000, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF]
!> F8000028  v6   = [0x40703FFF, 0xFFC00000, 0xFFC00000, 0xFFC00000]
!> F8000028  v7   = [0x3F800000, 0x3F800000, 0x3F800000, 0x3F800000]
!> F8000028  v8   = [0x00000000, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF]
!> F8000028  v9   = [0x00000000, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF]
!> F8000028  v10  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v11  = [0x40703FFF, 0xFFC00000, 0xFFC00000, 0xFFC00000]
!> F8000028  v12  = [0x7FC00000, 0x3F800000, 0x3F800000, 0x3F800000]
!> F8000028  v13  = [0x40703FFF, 0x3F800000, 0x3F800000, 0x3F800000]
!> F8000028  v14  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v15  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v16  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v17  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v18  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v19  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v20  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v21  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v22  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v23  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v24  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v25  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v26  = [0xB7364261, 0xB7364261, 0xB7364261, 0xB7364261]
!> F8000028  v27  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v28  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v29  = [0xFF800000, 0xFF800000, 0xFF800000, 0xFF800000]
!> F8000028  v30  = [0x40000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v31  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v32  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v33  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v34  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v35  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v36  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v37  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v38  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v39  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v40  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v41  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v42  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v43  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v44  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v45  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v46  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v47  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v48  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v49  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v50  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v51  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v52  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v53  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v54  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v55  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v56  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v57  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v58  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v59  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v60  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v61  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v62  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v63  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v64  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v65  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v66  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v67  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v68  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v69  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v70  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v71  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v72  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v73  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v74  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v75  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v76  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v77  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v78  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v79  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v80  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v81  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v82  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v83  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v84  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v85  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v86  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v87  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v88  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v89  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v90  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v91  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v92  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v93  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v94  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v95  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v96  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v97  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v98  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v99  = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v100 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v101 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v102 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v103 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v104 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v105 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v106 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v107 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v108 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v109 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v110 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v111 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v112 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v113 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v114 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v115 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v116 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v117 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v118 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v119 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v120 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v121 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v122 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v123 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v124 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v125 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]
!> F8000028  v126 = [0x00000000, 0x00000000, 0x00000000, 0x00000000]

```

**Comment by Gliniak** [comment]
Regression confirmed.
Caused by: 
https://github.com/xenia-project/xenia/commit/c2c263f34ad00bb3ddef8feebd85585e45acdf50
https://github.com/xenia-project/xenia/commit/eac7e2cd1f9ee15fb6447e325809462e49c1a349

I'm investigating what is wrong with it and why

**Comment by Graslu** [comment]
The game's singleplayer campaign is fully playable from start to finish on the latest builds, as long as you don't risk rolling. Rolling will sometimes cause the game to softlock, giving the player a black screen and 1fps until you pause and restart the mission or load a checkpoint.

Other than that, as I mentioned you can fully complete the game, it has a few minimal graphical issues such as z-fighting decals, some sounds won't loop properly, and cutscene music / audio will some times stop working. Even at unlocked framerate the game works really well. Multiplayer deathmatch is also inaccessible as Xenia doesn't support user profiles. (?)

I'm attaching a video showing the roll issue, alongside the log file.

https://user-images.githubusercontent.com/34986384/166825476-fa2ba246-034e-4dd2-9561-5e555d67fa81.mp4

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/8627203/xenia.zip)

**Comment by NuKe5369** [comment]
im suprised you guys are able to get somewhere in this game. I have a pretty high end maschine ryzen 5 5600x with a 2060 super and 32 gb of ram yet the game crashes either when i roll 3-4 times or at random. I cant even finish the first mission sadly :(

**Comment by Graslu** [comment]
> im suprised you guys are able to get somewhere in this game. I have a pretty high end maschine ryzen 5 5600x with a 2060 super and 32 gb of ram yet the game crashes either when i roll 3-4 times or at random. I cant even finish the first mission sadly :(

Yes, as reported above that's a known issue, the game doesn't really crash it just softlocks as you can press Start and restart the mission. You can 100% the game if you never roll, something that makes it almost impossible for harder difficulties.

**Comment by Machina74** [comment]
From my experience, it's not the roll that's making the game crash, it's the _waypoints_ and roll. I had waypoints turned off and was able to roll multiple times just fine. But as soon as turned waypoints on and did a roll, the game crashed. 

My theory is that Xenia has some problem with PD0 shifting from 1st to 3rd person while waypoints are turned on.

**Comment by Machina74** [comment]
> > im suprised you guys are able to get somewhere in this game. I have a pretty high end maschine ryzen 5 5600x with a 2060 super and 32 gb of ram yet the game crashes either when i roll 3-4 times or at random. I cant even finish the first mission sadly :(
> 
> Yes, as reported above that's a known issue, the game doesn't really crash it just softlocks as you can press Start and restart the mission. You can 100% the game if you never roll, something that makes it almost impossible for harder difficulties.

From my experience, it's not the roll that's making the game crash, it's the waypoints and roll. I had waypoints turned off and was able to roll multiple times just fine. But as soon as turned waypoints on and did a roll, the game crashed.

My theory is that Xenia has some problem with PD0 shifting from 1st to 3rd person while waypoints are turned on.

**Comment by Graslu** [comment]
> From my experience, it's not the roll that's making the game crash, it's the waypoints and roll. I had waypoints turned off and was able to roll multiple times just fine. But as soon as turned waypoints on and did a roll, the game crashed.
> 
> My theory is that Xenia has some problem with PD0 shifting from 1st to 3rd person while waypoints are turned on.

I don't think that's the case, because there are no waypoints on harder difficulties and it still happens. On my video example above there's also no waypoints either. Unless the setting itself has a side effect in the background, which I'd have to test.

**Comment by Machina74** [comment]
All goo

> > From my experience, it's not the roll that's making the game crash, it's the waypoints and roll. I had waypoints turned off and was able to roll multiple times just fine. But as soon as turned waypoints on and did a roll, the game crashed.
> > My theory is that Xenia has some problem with PD0 shifting from 1st to 3rd person while waypoints are turned on.
> 
> I don't think that's the case, because there are no waypoints on harder difficulties and it still happens. On my video example above there's also no waypoints either. Unless the setting itself has a side effect in the background, which I'd have to test.

All good man, just wanted to provide a lead it case it could help. But I did just try it again, and same thing happened. 3 rolls, no waypoints, no problem. Turned waypoints on, 2 rolls, game crashed.

**Comment by Graslu** [comment]
> 
Tried it again with the waypoints setting off and it still crashes on my end with the latest build.

**Comment by Graslu** [comment]
The game is finally playable start to finish with no game breaking issues or crashes. Here are a few of the problems I've picked up on a recent playthrough:

- Cutscene audio is generally broken. Sometimes it works, mostly it doesn't. Dialogue cuts off, music won't play, ambient sounds won't play.
- Loading screen music is broken, sometimes it will stutter and most of the time it won't play.
- Looping sounds don't loop, like the sword shield, hawk bubble shield, vehicles like dropships or ziplines.
- The graphic effect of disappearing bodies in multiplayer is missing.
- Playing multiplayer games and then going back to the main menu crashes the emulator.
- Lots of z-fighting textures on the snow levels (Mission 4) and desert (Mission 12).

Another thing that happens when playing at higher resolution than 720p is random black screen stutters, but I understand this is not a priority right now.

Here's the playthrough where all these issues listed above can be seen: https://youtu.be/ximJqgku3t8

Other than that, amazing progress in the emulator overall. Amazing to see this game playable at 60FPS finally.

**Comment by chrisps** [comment]
The rolling crash was fixed on canary by https://github.com/xenia-canary/xenia-canary/pull/50

likely required the higher precision dot product

**Comment by WonDerTeam1337** [comment]
> The rolling crash was fixed on canary by [xenia-canary/xenia-canary#50](https://github.com/xenia-canary/xenia-canary/pull/50)
> 
> likely required the higher precision dot product


all sound are broken no dialogue or weapon sound and cutscene also

**Comment by WonDerTeam1337** [comment]
Cut scene ate still glitched with no sound at all idk how to fix it

**Comment by Graslu** [comment]
> Cut scene ate still glitched with no sound at all idk how to fix it

There's no fix. The issues I listed at in https://github.com/xenia-project/game-compatibility/issues/175#issuecomment-1264858188 are all still present.

**Comment by WonDerTeam1337** [comment]
Ok

**Comment by parabolee** [comment]
Was able to fix audio bugs with -

use_dedicated_xma_thread = false

**Comment by Graslu** [comment]
Very nice! I can confirm that this fixed the loading screen music and cutscenes. However the looping sounds are still broken,

**Comment by parabolee** [comment]
Game looks fantastic in 4k with the following =

draw_resolution_scale_x = 2 
draw_resolution_scale_y = 2 

But I get screen flickering (millisecond of black screen it seems). Anyone have ideas how to fix?

**Comment by Graslu** [comment]
Here's a short video showing the issues left to fix in this title other than crashes (backing out of multiplayer matches back to the main menu and checking the game leaderboards):

- Lots of z-fighting textures on the snow levels (Mission 4) and desert (Mission 12). Basically most decals cause z-fighting.
- Looping sounds don't loop.
- The graphic effect of disappearing bodies in multiplayer is missing. At the end I show how it's supposed to look.

https://github.com/xenia-project/game-compatibility/assets/34986384/fa05a140-ab40-499b-be45-54ad363517b5

**Comment by Graslu** [comment]
Changing `render_target_patch_d3d12 =` to `rov` fixes the z-fighting textures!

![image](https://github.com/xenia-project/game-compatibility/assets/34986384/173b3371-5840-47c6-9d8d-68de8561a418)

For some reason the first time I tried ROV caused this crash to happen but after a restart it's working fine, and the initial lag is gone after shader compilation:

![GQS_vGXWoAASUlY](https://github.com/xenia-project/game-compatibility/assets/34986384/2535d418-677e-407c-8e40-93cf2f4e2c67)

**Comment by parabolee** [comment]
Awesome work! We are so close to running this perfectly. If we could just get it to render in 4k! The last few issues are super minor after that. Although I'd really love to be able to check my stats after a mission without it crashing. I have started screenshoting them and restarting so can keep track of my scores. 

I love this game so much it brings joy to my heart to replay it in prep for the new game. Especially with 60fps mostly fixing the games biggest issue (input lag). I'd also love to get online co-op working.

**Comment by Graslu** [comment]
When using ROV, the only graphical issues I've found are these:

The holograms only render correctly when you're standing in front of them, this does not happen on Xbox 360 or One / Series.
![image](https://github.com/xenia-project/game-compatibility/assets/34986384/6f2f5a7b-6eb3-43f9-8217-599761b9ef82)
![image](https://github.com/xenia-project/game-compatibility/assets/34986384/ea422d17-30d7-47f1-b1ac-c0d066b859f0)
![image](https://github.com/xenia-project/game-compatibility/assets/34986384/c61b8925-f899-45ad-b787-f2c197361f5e)
![image](https://github.com/xenia-project/game-compatibility/assets/34986384/a2fa3b27-3e00-4235-8e2c-59f68068f951)



Zhang Li's face has broken shading.
![image](https://github.com/xenia-project/game-compatibility/assets/34986384/de5cc145-cd72-4a0e-9908-9af852e56713)

Same broken effect when dying in multiplayer, the effect is just missing. Fun fact: While this effect is present on Xbox One X, on Series X when running the game at higher resolution it's just missing, too. https://github.com/xenia-project/game-compatibility/issues/175#issuecomment-2172363903

**Comment by cybernaut4** [comment]
> Was able to fix audio bugs with -
> 
> use_dedicated_xma_thread = false
> 
> Have not tested extensively yet but cut scenes that previous were missing many sounds played perfect on several tests.

Where do you set this? I tried creating a `portable.txt` in the same directory as the executable, but it made no difference... and the [Options page](https://github.com/xenia-project/xenia/Options) link (in the FAQ) is broken.

**Comment by parabolee** [comment]
> > Was able to fix audio bugs with -
> > use_dedicated_xma_thread = false
> > Have not tested extensively yet but cut scenes that previous were missing many sounds played perfect on several tests.
> 
> Where do you set this? I tried creating a `portable.txt` in the same directory as the executable and pasted that line, but it made no difference... and the [Options page](https://github.com/xenia-project/xenia/Options) link (in the FAQ) is broken.

In the xenia-canary.config.toml file.

**Comment by cybernaut4** [comment]
I found it at `Documents/Xenia/xenia.config.toml`

There's no pre-existing "use_dedicated_xma_thread" option in the toml file so I added it at the end of file.

But still didn't make a difference... my guess is it should be under a specific "header" (if that's the name for it)?

**Comment by parabolee** [comment]
> I found it at `Documents/Xenia/xenia.config.toml`
> 
> There's no pre-existing "use_dedicated_xma_thread" option in the toml file so I added it at the end of file.
> 
> But still didn't make a difference... my guess is it should be under a specific "header" (if that's the name for it)?

Oh you need to use the Canary build.

**Comment by cybernaut4** [comment]
> > I found it at `Documents/Xenia/xenia.config.toml`
> > There's no pre-existing "use_dedicated_xma_thread" option in the toml file so I added it at the end of file.
> > But still didn't make a difference... my guess is it should be under a specific "header" (if that's the name for it)?
> 
> Oh you need to use the Canary build.

Turns out the config file is in the same folder as the executable.
Named `xenia-canary.config.toml`.

Thank you!

**Comment by Margen67** [comment]
Xenia Canary issue: https://github.com/xenia-canary/game-compatibility/issues/77

**Comment by jovantancic** [comment]
Any chance making Perfect Dark Zero support mousehook like XBLA? It's about God damn time. I'm not playing this with gamepad.

**Comment by jovantancic** [comment]
I am trying GPDSCK to play Perfect Dark Zero. I am not using my gamepad to play this game, but want to experience it with keyboard and mouse. So far it's doing a great job, but my mouse sensitivity is so damn low even having it set at 150. Any idea what could I do to increase mouse sensitivity? Perhaps some different program?
