### ISSUE TITLE
534307D5 - Just Cause

### ISSUE THREAD

**Issue by Blackbird88** [xenia-project/game-compatibility#215]
[Marketplace](http://marketplace.xbox.com/en-US/Product/Just-Cause/66acd000-77fe-1000-9115-d802534307d5)

Tested with benvanik/xenia@64b8dcf

* Hangs on title screen while loading, shows assert and crashes

![image](https://cloud.githubusercontent.com/assets/4414625/10713369/09d5ae18-7abc-11e5-8943-3ea2962e40f2.png)

[Log](https://gist.github.com/Blackbird88/5a8b1c3541358d18cb4f)

![image](https://cloud.githubusercontent.com/assets/4414625/10713360/7a154e82-7abb-11e5-91ef-c77d725a94ff.png)

**Comment by Kattus** [comment]
Now shows first intro then crashes.
![](https://i.imgur.com/U08ztcJ.png)
![Log file](https://gist.github.com/df869251d572ee479259cccf58aa8ed5) - state-intro

**Comment by Razzile** [comment]
hello darkness my old friend

**Comment by Blackbird88** [comment]
Weird. It always crashes after the loading for me.

**Comment by Blackbird88** [comment]
Gets into menu now
![image](https://cloud.githubusercontent.com/assets/4414625/17224754/8c6dbcd2-5502-11e6-8c6c-52be421147d5.png)

**Comment by Blackbird88** [comment]
Gets in-game now with broken graphics
![image](https://user-images.githubusercontent.com/4414625/40580338-8117585a-613c-11e8-94ca-9014cf8918c6.png)

**Comment by Blackbird88** [comment]
the d3d12 branch
![image](https://user-images.githubusercontent.com/4414625/46101181-93faa900-c1cb-11e8-9616-81773ca7ba41.png)

**Comment by NovaPrima** [comment]
Looks perfect.

**Comment by adolfintel** [comment]
Just a quick update on this. As of commit cf0251cd I was able to play the first few hours of the game without crashes. There are 2 problems:
* Videos don't play correctly, they flicker between the first 2 frames. This seems to have already been fixed in canary
* There's artifacting near the water, seems to be on the "wet sand" material more than the water itself (see screenshot below, also present on canary)

Everything else seems to be rendered correctly, performance is rock solid, this game can be considered playable if those issues are fixed.

![2020-04-23 11_36_04-Window](https://user-images.githubusercontent.com/16307689/80083911-71bb3f80-8556-11ea-8b42-9693a831c4c0.png)

Intel Core i9 9900k
nVidia GTX 1080
Windows 10

**Comment by Margen67** [comment]
@adolfintel Please provide a log.

**Comment by adolfintel** [comment]
@Margen67 here you go: 
[xenia.log.zip](https://github.com/xenia-project/game-compatibility/files/4521724/xenia.log.zip)

**Comment by HALT77** [comment]
it is still in the same state...the water glitches are still present.

**Comment by kortul** [comment]
Still the same state with black bars over the water. Also when you or NPCs shoot the guns - grass textures flicker.

**Comment by Margen67** [comment]
Xenia Canary issue: https://github.com/xenia-canary/game-compatibility/issues/185

**Comment by Kukuruzka4444** [comment]
#[kortul](https://github.com/kortul)
> * [ ]  -Might crash during M5 Test of Loyalty, when getting close to the truck:
> 
> ![crashzoneJC1](https://private-user-images.githubusercontent.com/103463244/346150337-e7b798fc-bda1-448b-8756-725d556a9b82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDAyMTIsIm5iZiI6MTcyODg5OTkxMiwicGF0aCI6Ii8xMDM0NjMyNDQvMzQ2MTUwMzM3LWU3Yjc5OGZjLWJkYTEtNDQ4Yi04NzU2LTcyNWQ1NTZhOWI4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwOTU4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWI1ZDI4MmExNGNkOWM0NDc2ZWFlM2JlYWE0M2IxZmJlMzc2NmMzNjk1MTUzYjQxOTFhODNmNDQwNGRlYWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eC7q9cpvHz8fjm-NWkAuClwDrKNvpVIFyiHm_x-7UZU)
>
> * [ ]  - The small area of the map from the Mission 5 mentioned above causes crashes when approached near the point where collectible is on the map right beneath the garage where the truck is in M5. This makes picking up that collectible and finishing the race in that area problematic. Something in that area causes the crash and the only way to avoid it is by averting the camera away from it.

Here's a video guide on how to obtain the black box collectible in the crash area next to the Mission 5 base:

[https://imgur.com/pmRBZcq](https://imgur.com/pmRBZcq)

There should be no issues with the race event there, if the camera is pointed roughly away from the collectible.

**Comment by rrrcabral** [comment]
with me on latests canary remains the bug "Black bars over the water"

**Comment by Margen67** [comment]
> with me on latest canary remains the bug:
> 
>     * Black bars over the water
> 
>     * freeze/crash in the mission 'blowing up the silos'
> 
> 
> Does anyone have a save file to share immediately after completing this problematic mission?

@rrrcabral Xenia Canary discussion belongs in the issue I posted above.

**Comment by rrrcabral** [comment]
I managed to get through this mission by following the tip of approaching the truck without looking directly at it, walking with the camera facing the other way, after getting the truck then leaving this silo location and taking a road towards the objective on the map.
To make it easier for those who can't do this, here is a SAVE file after completing the mission:
https://drive.google.com/file/d/10-wTR09hlzAwE06EyZPFZemSbIQCApkT/view?usp=sharing
