### ISSUE TITLE
454107F9 - Battlefield: Bad Company

### ISSUE THREAD

**Issue by theoldsport** [xenia-project/game-compatibility#244]
Able to get into the menu and start loading the game. Video here- https://www.youtube.com/watch?v=iol11HNgepw
![bc1](https://cloud.githubusercontent.com/assets/13494133/11168711/bd2e0de6-8b58-11e5-916e-a46abf6bd025.png)

**Comment by Blackbird88** [comment]
Menu is semi-broken now instead of being black.
![image](https://cloud.githubusercontent.com/assets/4414625/11975748/3cb4fe36-a971-11e5-9753-5a4d310bb3ef.png)

**Comment by Blackbird88** [comment]
Menu is fixed now
![image](https://cloud.githubusercontent.com/assets/4414625/17224926/3c3306ea-5503-11e6-9582-2b1582d8abc8.png)

**Comment by Insane11** [comment]
Black screen, but menu sound is playing.
![62ee2f7c620847b29fe7dc9241fa9350](https://cloud.githubusercontent.com/assets/25592138/22659560/18d717ce-ecaf-11e6-8597-929792155b6e.png)

**Comment by zumbuh** [comment]
I heard sound of the game in the background before it crashed for me.

**Comment by somereallygoodname** [comment]
No longer crashes and is able to play through the first cutscene and mission. Graphics are still buggy, but do note I was testing on an AMD graphics card. Will be trying on NVIDIA in a few hours. Framerate is decent (25-30fps) yet there's lots of stutter. Sometimes the characters will repeat themselves, and some sound fx are missing (explosions on buildings are silent). Not sure which build it started on, I am using https://github.com/benvanik/xenia/commit/e4bc5968870f55cbebedb0aba5a5cb30a1962fa3 Video: https://www.youtube.com/watch?v=Cwx9GGnTedI

New tags: state-gameplay, gpu-corrupt-drawing

**Comment by stride21** [comment]
Menu broken and crashes just before going ingame using Nvidia GPU. 
Tested on (xenia-project/xenia@ba7dc6b)

![bc1](https://user-images.githubusercontent.com/37915864/43040443-9cb00118-8d09-11e8-8475-2a014b682b3b.JPG)
![bc2](https://user-images.githubusercontent.com/37915864/43040444-9eb24804-8d09-11e8-8cda-7772eff8ff7a.JPG)
[xenia log.zip](https://github.com/xenia-project/game-compatibility/files/2216546/xenia.log.zip)

**Comment by emoose** [comment]
Goes ingame with latest d3d12 after waiting for a little on the loading screens, cutscenes seem to play out fine with some minor audio popping issues, during gameplay it tends to stutter a lot though but that could just be my rig.

![xenia_(detached211f5974Jul_21_2019)__ 454107F9 _2019-07-27_13-48-45](https://user-images.githubusercontent.com/1755499/61994713-02bbc380-b076-11e9-807d-db3f1a861529.png)
![xenia_(detached211f5974Jul_21_2019)__ 454107F9 _2019-07-27_13-49-02](https://user-images.githubusercontent.com/1755499/61994714-08190e00-b076-11e9-9e68-47448e709373.png)

**Comment by FitterSpace** [comment]
### Tested on https://github.com/xenia-project/xenia/commit/f748e5af49062fd78d098acdaf045183f29faf36

The emulator closes itself during the loading screen after starting the single-player campaign. My situation is similar to stride21.

### Log: 
[BadCompanyCrash.zip](https://github.com/xenia-project/game-compatibility/files/3665776/BadCompanyCrash.zip)

**Comment by Etokapa** [comment]
Tested on https://github.com/xenia-project/xenia/commit/9a74df491ffd0189ddd26bc2030e0eae6a775f4e

Loaded a save file and completed the artillery strike objective. 30FPS on 2x resolution with vsync on and shaders cached.
Started a new game and calibrated controls. I wasn't able to move my character to meet the NPC, Stillwater, causing a softlock. This wasn't the case months ago. No graphical issues.

:warning:Everything will be dark unless you set `d3d12_readback_resolve=true`. This will severely impact performance though.

![bbc (4)](https://user-images.githubusercontent.com/31154606/105774715-402f3480-5f2b-11eb-8a1a-fcef7ddef258.png)

<details>
  <summary>More Screenshots</summary>

![bbc (1)](https://user-images.githubusercontent.com/31154606/105774726-458c7f00-5f2b-11eb-8264-1fcabd730e54.png)
![bbc (2)](https://user-images.githubusercontent.com/31154606/105774728-458c7f00-5f2b-11eb-900f-496b7cfbeb4b.png)
![bbc (3)](https://user-images.githubusercontent.com/31154606/105774729-46251580-5f2b-11eb-9c6f-3047a1628471.png)
![bbc (5)](https://user-images.githubusercontent.com/31154606/105774730-46251580-5f2b-11eb-8945-dbfd0611ecd5.png)

</details>

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5870063/xenia.zip)

gpu-readback

**Comment by oreomaniak** [comment]
Tested on [xenia-canary/xenia-canary/releases/tag/d2f4bf048](https://github.com/xenia-canary/xenia-canary/releases/tag/d2f4bf048)

Issue: NPC's sound like animal crossing characters (looping), video link: https://www.youtube.com/watch?v=22zn7bCxVHY

otherwise, game seems okay. Has crashed multiple times around the repair vehicle part of the first level (around the time frame in the video above).

Ryzen 5 2600x OC @ 3.9 & GTX 1080

**Comment by insaneninja117** [comment]
Tested on master@3a115ae6a (Apr 14 2022) build from a blank save. Intro videos play fine and main menu is navagiable. After watching the behind the scenes video all the way through (Gold Edition copy) loading up the campaign causes Xenia to crash (without first reporting a guest crash).

Main menu suffers from some graphical corruption.

PC Specs:
Windows 7 SP1 Professional
Intel Core i3-6100
AMD Radeon Pro WX3100
8GB DDR3

![BFBC 1](https://user-images.githubusercontent.com/38947445/163675935-dca5066e-a289-4f3d-b1a4-1f6e9c2346bd.jpg)

[Xenia Log BFBC.zip](https://github.com/xenia-project/game-compatibility/files/8499987/Xenia.Log.BFBC.zip)

**Comment by DubZeroSP** [comment]
Tested on https://github.com/xenia-project/xenia/commit/ed64e3072bde74955c79b9f3b0030c133648d702
Intro videos as well as the main menu are fine, first cutscene as well gameplay initially load.
In the cutscenes there is stuttering and audio cuts alot - after you pass the first cutscene and load into the ditch, the stuttering disappears entirely, but the characters speak like they are in Animal Crossing and when attempting to shoot the barrel as told by the tutorial, it crashes the game.

https://drive.google.com/file/d/1gityW_tmeWAaot7rEMMdZey2uPM-rT6b/view?usp=share_link (xenia.log)

**Comment by DubZeroSP** [comment]
Tested on https://github.com/xenia-project/xenia/commit/6ee2e3718f81748f3f2c6cae7287dffa7f87b14e
Made it to the artillery section and the game crashes as soon as the explosions start.
Previous audio issues are still present.

**Comment by DubZeroSP** [comment]
Tested on https://github.com/xenia-project/xenia/commit/4a3b04d4ee90f31f08e7aa7ab30228c3eebe1d85
Same as previous comment

Tested on https://github.com/xenia-canary/xenia-canary/commit/921923472b48f3e29f695cda196be3d63a3b28cb
Apart from shadows and some smoke effects the game works remarkably well - I'd call it playable!
[Recording included](https://youtu.be/lRLn7YSlhkI)

**Comment by cwook** [comment]
When using the 60fps patch, there are certain areas that run too fast.
