### ISSUE TITLE
534507D6 - Sonic the Hedgehog

### ISSUE THREAD

**Issue by Ichigo14** [xenia-project/game-compatibility#285]
Playable with major glitches 

![sonic3](https://cloud.githubusercontent.com/assets/16140062/11677228/7d27a516-9e4c-11e5-9b5b-1661954e5efc.jpg)
![sonic](https://cloud.githubusercontent.com/assets/16140062/11677229/80356932-9e4c-11e5-8313-0ffb8924eed7.jpg)
![sonic2](https://cloud.githubusercontent.com/assets/16140062/11677230/825a99d0-9e4c-11e5-9f43-e26d4df6f29a.jpg)

**Comment by Ichigo14** [comment]
Tested on EmuCR-Xenia-20151215.

title screen it's ok now

![xenia333333](https://cloud.githubusercontent.com/assets/16140062/11834336/a53d9958-a3dc-11e5-8b5f-0ce028d1c326.jpg)

**Comment by Lumadash** [comment]
Wow! Good progress. do the other episodes of the game work as well? Do you have any pictures for them?

**Comment by Solarstrike** [comment]
Jeez, that looks like '06 on PC.

**Comment by cmexp** [comment]
It seems a new bug has popped up on certain hardware configurations for this game in later builds.

I noticed that certain actions would kill me instantly while showing me a black screen (or a frozen screen) until respawn. And watching videos of people playing the game on the same builds I was testing this on, it seems the bug is not affecting them. The system I was testing this on had a GTX 980, Intel 5930k, DDR4 2133 RAM, and Windows 10.

The things that trigger this are:

- [Light dashing in midair](https://gfycat.com/IndelibleAcrobaticArabianhorse) ([compared to when not in midair](https://gfycat.com/IndelibleValidBalloonfish))

- [Certain bounce pads](https://gfycat.com/SpiritedClutteredBunting)

- [Grabbing onto the whale in this scripted event](https://gfycat.com/ImmaculatePaltryEyra)

**Comment by theoldsport** [comment]
@cmexp I'm getting the same behavior on the latest build, plus physics is all over the place. How did you get around the half-screen + swapped color palette?
ex-
![ex](https://cloud.githubusercontent.com/assets/13494133/15003528/9e6bf3fc-1161-11e6-9b14-4e5e6db5dab3.png)

**Comment by cmexp** [comment]
@theoldsport I extracted the contents of the ISO file (using the software "Xbox 360 ISO Extract") and put [this file](http://www.mediafire.com/download/jqt4j50kt55300j/cache.rar) into the xenon\archives\ directory. Then I loaded the game by clicking the .xex executable in the extracted game folder.

**Comment by theoldsport** [comment]
@cmexp Oh... well that's cheating! I guess my screenshot is the more accurate representation of how the game currently runs (unmodded)

**Comment by cmexp** [comment]
To be fair, it's only the graphics that are fixed. The physics are still all over the place in the modded game.

**Comment by Lumadash** [comment]
I've tested the Xbox Live Demo version of Sonic the Hedgehog, and it is very buggy. The screen is mostly red, very slow, and the screen fades black after jumping.

**Comment by SilverSzymonPL** [comment]
Eh, the game was already buggy as f^%&k. I don't even know why anyone bothers to make it playable.

**Comment by SilverSzymonPL** [comment]
Still don't know if sound is emulated

**Comment by Parovozik** [comment]
@SilverSzymonPL This half-playable (Sound OK, but some broken graphics and game mechanics)
LvL Crysis City (Vulkan) https://www.youtube.com/watch?v=CjHccEYhz5g
 LvL Ocean Wave (OpenGL) https://www.youtube.com/watch?v=h_Jr5GbuSI8

**Comment by HorrorTroll** [comment]
![image](https://cloud.githubusercontent.com/assets/24840279/22060600/06b46584-dda4-11e6-9338-9f63d4dee212.png)
![image](https://cloud.githubusercontent.com/assets/24840279/22060644/3364eafe-dda4-11e6-947f-4596d3ff097b.png)
![image](https://cloud.githubusercontent.com/assets/24840279/22060664/4780398a-dda4-11e6-82b1-e4144b4d63cf.png)
![image](https://cloud.githubusercontent.com/assets/24840279/22060694/63e3d5be-dda4-11e6-9293-c7538fa8bf23.png)
![image](https://cloud.githubusercontent.com/assets/24840279/22060747/ac88e034-dda4-11e6-8f89-6268e4d2dd08.png)
![image](https://cloud.githubusercontent.com/assets/24840279/22060859/2b70a210-dda5-11e6-8c5f-013c4fddc6dc.png)

It work everything right texture all of NPC, the camera have a little buggy on wave ocean like before. The rings, background, sonic spikes on head it has been many error!!

This is the test on OpenGL in build (https://github.com/benvanik/xenia/commit/5b8b339c388a0ff4c8be113d46bc30b5dc3bd5e4)

On Vulkan test is just a black screen only hear the sound, button working!!!

**Comment by jthecodebuilder** [comment]
Why does the XBL demo crash when it gets to "d> 00000010 XAudioSubmitRenderDriverFrame(41550000, 401F9D80)"?

**Comment by Irixion** [comment]
The demo crashes when using the Vulkan API, just as the level starts. 
W10, AMD R9 270X, Vulkan

The retail release is fine with Vukan on AMD, but has depth issues (surfaces that are supposed to be on top of things because they're closer appear behind things). It does run better so that's a plus. I'll grab some screenies and throw then up when I have time.

**Comment by Irixion** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26639385/24374869/65fe2f62-1304-11e7-929b-0e2d1366330c.png)

Here's the best depth issue example I can get. The spring is inside the box, but it appears on top. Other level assets do the same, including Sonic's model.

**Comment by jthecodebuilder** [comment]
I have a Nvidia GPU, not AMD.

**Comment by Irixion** [comment]
Try updating your build, it shouldn't crash now. For me, it was just a temporary regression for one or two builds. Really hoping that AMD users will see some more parity with their nVidia counterparts. GL runs like molasses compared to the Vulkan...though without game modification the game doesn't draw any 3D assets.

**Comment by Irixion** [comment]
[https://gist.githubusercontent.com/Irixion/30a55942162bccdb5046357d3e4e70cb/raw/e29c7bbab465fad78d65e0bf5bfb8289a53be698/xenia.log](url)

Here's the log. Specifically this bit:

> w> 00000004 GPU: Write to unknown register (045E = 00000004)
> w> 00000004 GPU: Write to unknown register (045E = 00000004)
> w> 00000004 GPU: Write to unknown register (045E = 00000004)
> w> 00000004 GPU: Write to unknown register (045E = 00000004)

Lots of unknown register warnings.

**Comment by slashiee** [comment]
On latest master, it crashes at beginning loading on Vulkan. Using AMD GPU and CPU

Windows 10 (64 bit)
AMD FX(tm)-6300 Six-Core Processor
AMD Radeon (TM) R7 360 Series

Log file:
[xenia.txt](https://github.com/xenia-project/game-compatibility/files/948738/xenia.txt)

**Comment by Parovozik** [comment]
Tested on (https://github.com/benvanik/xenia/commit/cecc66622f278ca057e19afe86768af6dfe640ba)

# Issues:
Vulkan. Color bug, invisible hair on Sonic
OpenGL. Invisible hair on Sonic
Core. Black screen bug if uses triple jump-pad (not freeze, not chash, game restarting from last checkpoit), black screen bug on dolphin (there auto change character but go on restart from last checkpoint). Sometimes blackscreen bug on circle-jump. Sometimes no physics (collision?) and Sonic falls through (example qte on jumping), but if locked 30fps then this works more good (but slow-mo ingame speed)
Audio - OK. Performance is good.

# Logs:
[Sonic_Vulkan_60FPS.txt](https://github.com/xenia-project/game-compatibility/files/949357/SonicVK60FPS.txt)
[Sonic_Vulkan_30FPS.txt](https://github.com/xenia-project/game-compatibility/files/949358/SonicVK30FPS.txt)
[Sonic_OpenGL.txt](https://github.com/xenia-project/game-compatibility/files/949359/SonicOGL.txt)

# Video:
[YouTube_Sonic_Vulkan](https://www.youtube.com/watch?v=rCTqSpjWFY0)

# Screenshots:
Vulkan:
![desktop 04 23 2017 - 01 48 39 02 mp4_snapshot_01 26_ 2017 04 23_02 22 13](https://cloud.githubusercontent.com/assets/19775644/25309087/fe19ce92-27cb-11e7-853c-faa2db63634e.jpg)
Vulkan:
![desktop 04 23 2017 - 01 48 39 02 mp4_snapshot_00 42_ 2017 04 23_02 23 36](https://cloud.githubusercontent.com/assets/19775644/25309088/fff9c032-27cb-11e7-9601-405b6de1d1cd.jpg)
OpenGL:
![desktop 04 23 2017 - 02 00 41 04 mp4_snapshot_01 18_ 2017 04 23_02 24 09](https://cloud.githubusercontent.com/assets/19775644/25309090/0e824dfe-27cc-11e7-814e-88fb0ef873cf.jpg)

# Labels:
gpu-corrupt-drawing
cpu-timing (?)
state-gameplay

**Comment by Irixion** [comment]
@slashiee  Your issue is caused by AMD's drivers. Upgrading to the latest drivers causes it to crash on my system as well. Removing them and letting Windows install them allows it to function properly.

@Parovozik The black screen "bug" is a crash handler in the game. It just kills you when it doesn't know what to do and reloads from the last checkpoint. As far as collision, the game's logic runs at 60 fps. If capped to 30, some unusual things may happen.

**Comment by Irixion** [comment]
https://www.youtube.com/watch?v=eTrbLqsxncc - Vulkan

https://www.youtube.com/watch?v=fOsP-yF-mXI -  OpenGL

On the latest build, using the modified cache.arc file.

**Comment by Parovozik** [comment]
Tested on (https://github.com/benvanik/xenia/commit/84758a3a3faa03aed86611380ead1660f2e4657b)
Now colors more correct, but still bugs as triple-jump-pad and etc
[YouTube_Sonic2006_Vulkan](https://www.youtube.com/watch?v=5-1OsHw985Y)

**Comment by Irixion** [comment]
Can the labels be modified to include:
gpu-missing-drawing
cpu-timing

Currently I get a black screen with just HUD elements on Vulkan, but I'll try the newest build once I get home. AMD 😥

**Comment by Irixion** [comment]
https://www.youtube.com/watch?v=R344TIDtbss

I'll get a screenshot tomorrow.

**Comment by AllanCat** [comment]
# FIXED
I've just fixed the jump pad and camera error by rolling back two sections of code in xenia-cpu:
1. Commented out OPCODE_SPLAT in constant_propagation_pass.cc
This is the main reason that cause various games's camera and vertices go wrong ([PR#514](https://github.com/benvanik/xenia/pull/514))
2. Rollback InstrEmit_fcmpx_ in ppc_emit_fpu.cc:
This causes Sonic dies immediately when hit a wall or some slopes. ([Commit#66dbd86](https://github.com/benvanik/xenia/commit/66dbd869894c7484be4a8c6212a953efa955a589))

You can find the exactly changes on [my forked branch](https://github.com/AllanCat/xenia/commits/master) (Sorry about the space indentation lol)

# Video
https://www.youtube.com/watch?v=AaJQHpAxCxQ
Everything seems back to normal, the game is pretty much playable now 💯 

btw I don't know if this fixes/brakes the other games too, also I have literally zero acknowledge of 360 emulation. That'd cool if some developers can look into these codes. Should I raise a PR or Issue?

**Comment by Irixion** [comment]
I would say fixes, as I can get into some games I couldn't previously. PR pls? ✌️

**Comment by slashiee** [comment]
I still have no clue on how to get this game working on Vulkan. Even on my new computer, it crashes on boot. OpenGL works fine, though.

GeForce GTX 1060 6GB
Intel Core i5-7600K @ 3.80GHz
16GB RAM DD4-2133MHz

![image](https://user-images.githubusercontent.com/15317421/28096683-86c59c2c-665f-11e7-96ae-fbbc1b04277c.png)

**Comment by Irixion** [comment]
I have the same card. Though, make sure your drivers are up to date and that Vulkan is installed. Also, sometimes Xenia crashes for no reason when the log file exists. Try deleting that. Also try extracting the ISO's contents, and using the cache.arc replacement that's linked in this thread.

**Comment by AllanCat** [comment]
@slashiee 
Put this modified (cache)[https://drive.google.com/open?id=0B_9vQUilzHlNZVhLMFdLdXZsRFE] file to xenon\archives\ and it should be good to go.
@Irixion 
Okay sounds good, I'll manage my commits before PR(those spaces)

**Comment by slashiee** [comment]
@AllanCat Cache file works, thanks!

![image](https://user-images.githubusercontent.com/15317421/28096941-67e2ee8e-6661-11e7-899d-2f0cb560d0bf.png)

**Comment by Irixion** [comment]
There's only a couple of things that are still off with the game, though it's very close to perfect emulation. Hoping the Vulkan thread gets unlocked so we can discuss things. You're my hero @AllanCat

**Comment by gibbed** [comment]
@Irixion While it's nice a temporary workaround was found, reverting changes blindly is not going to be accepted as a PR. This however, can be taken note of and be investigated when a contributor has time to.

**Comment by AllanCat** [comment]
@gibbed 
Yes that's what I considered in my original post, glad to see your reply and hope this finding can help with future development. :)

**Comment by AllanCat** [comment]
Got some time messing around with cache file. You can get it from [here].(https://drive.google.com/open?id=0B_9vQUilzHlNRUd2VTdSd2ZBQ1E) 
1. Fixed map graphic issue as the original cache hack didn't render it properly. (core/render_radermap.lub)
2. OpenGL Speed up(by set GenerateCSMLevels and GenerateCSMObjects to 1), I'd say about ~20% faster though it still slows down at various situations(Too Much Water). At least it runs almost 60fps in crysis city and wave ocean.

Also by reducing audio buffer (kMaximumQueuedFrames in audio_sysrem.h) the latency feels better.

Video: https://www.youtube.com/watch?v=pOpKpM-N7xY
At this point I think I've already gone too far and done what I can with this game. Cheer up :D

**Comment by Irixion** [comment]
@owner Feels like there's regression with that in there though. The audio buffer (kMaximumQueuedFrames in audio_sysrem.h) though needs to be adjusted for Vulkan--the audio is slightly out of sync with the video.

@AllanCat Some levels set CSM levels for terrain and objects on their own. However, how did you manage to edit the lub file? Did you use chunkspy?

**Comment by AllanCat** [comment]
@Irixion 
There's exactly one [unluac fork](https://sourceforge.net/p/unluac/discussion/general/thread/74bc8a4b/) that supports for lua5.0, it still has problem about for loop. Here I'm just bypassing the error:
decompile\Registers.java
`
  public Target getTarget(int register, int line) {
    if(!isLocal(register, line)) {
      //throw new IllegalStateException("No declaration exists in register " + register + " at line " + line);
      //
      decls[register][line] = new Declaration("_TMP_", 0, 0);
    }
    return new VariableTarget(decls[register][line]);
  }
`
This is a bit off topic, I think we can discuss on other place(discord or so). Thanks!

**Comment by Irixion** [comment]
@AllanCat Thanks for shedding some light on that. Since Github doesn't have direct messaging, I'll message you via YouTube instead. Cheers!

**Comment by AllanCat** [comment]
Did some more researches about what works and what not, here's my progress so far:
# Video: 
https://www.youtube.com/watch?v=6GcLpbTM2QA

### Xenia issues:
Found three spots which broke a lot of games, still need to fix them instead of just reverting the commits. (mentioned [here](https://github.com/xenia-project/game-compatibility/issues/285#issuecomment-314017320) and [here](https://github.com/AllanCat/xenia/commit/cf21f9f99217367e73c3be0d4142658afce29a53))

### Common issues:
1. Not supporting MSAA caused game crash(vulkan) or glitched(gl).
Fixed by removing all MSAA parameters in cache file. Note that's probably the reason makes other games not working too.

2. Building&Character's shadow isn't cut correctly so that the whole ground became dark gray.
Fixed by removing all shadow effects, this speed up openGL a lot.

### Vulkan issues:
1. Color is darker than console/gl.
It's been [noted](https://github.com/benvanik/xenia/issues/578#issuecomment-228140769) maybe something wrong with channel swapping, hoping that can be fixed soon.

2. Some reflecting effect has wrong color map(like sea in town, Sonic's shoes and Amy's ring gloves)
This is probably caused by Vulkan not supporting k_2_10_10_10_FLOAT color format(GL can mapped this to GL_RGB10_A2), maybe we need to convert k_2_10_10_10_FLOAT to other formats.

### OpenGL issues:
1. Missing textures for all people in game, even Alise and Eggman.
I really don't know why. orz.

# Screenshots:
Some screenshots about the issues mentioned above:
https://imgur.com/a/K35Xb

**Comment by jackchentwkh** [comment]
will it be better to put those common issues to the issue list instead of burring here? even the vulkan issues are common issues since vulkan is now the only one being supported instead of GL.

**Comment by Irixion** [comment]
@jackchentwkh That would be great, but the Vulkan thread is locked. I think the only reason he's comparing the two is because GL supports some things that Vulkan doesn't, and it would be helpful to look and see how GL does it, to implement similar functionality to Vulkan.

@AllanCat I've sent you a message on YouTube. Did you get it?

As far as the textures for the townspeople, I think that it's got something to do with the CPU instructions that were reverted as it worked for me in earlier builds.

**Comment by AllanCat** [comment]
@Irixion Sorry I just noticed your youtube msg now ;p
I'm assume your earlier build was used old cache patch [like here](https://github.com/xenia-project/game-compatibility/issues/285#issuecomment-273443070), the color you saw was not actually a texture. This cache applied a built-in shader called "simple" which simply draws solid color when rendering objects. I was messing around to try if I can apply it only on people and I failed. :c It affects too many objects and is not useful at all.

**Comment by DoctorGibuz** [comment]
Crashes when choosing an episode for me using a hacked cache and OpenGL.
![screenshot_26](https://user-images.githubusercontent.com/24657200/28501958-bacd74f2-6fdf-11e7-9544-8e88a061696b.png)

**Comment by jackchentwkh** [comment]
May I ask what tool you guys used to trace/debug the shader?

**Comment by Irixion** [comment]
We looked at the game's rendering pipeline to see exactly what it was doing, and compared that to what Xenia does. That being said--what's your crash log say? The last line? What back end are you using? What's your hardware?

**Comment by DoctorGibuz** [comment]
Specs:
OS: Windows 10 64 bit
GPU: Radeon R7 Graphics
CPU: Radeon R7 A750k 3.3ghz Quad Core
Ram: 16GB

I tried using Vulkan but everytime i do it crashes, i assume this is because of the fact i haven't got a Vulkan GPU yet.

Anyway here's the log


[CrashLog.zip](https://github.com/xenia-project/game-compatibility/files/1185324/CrashLog.zip)

**Comment by Irixion** [comment]
@DoctorGibuz 

AMD cards don't support a format required by Xenia to run.

**Comment by Kooold** [comment]
![uggzvdqttjafd9-wyctomq](https://user-images.githubusercontent.com/30683237/28908057-a9938f88-7821-11e7-9c41-bc0e72438e48.png)
Strange bug at the start of a shadow mission, any idea? 
It seems that this problem only happens to me :/

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/1196130/xenia.zip)

**Comment by lumo93** [comment]
Specs:
GPU: GeForce GTX 1050 Ti 4GB
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz Skylake
Memory: 16 GB RAM
Operating system: Microsoft Windows 10 Pro
Vulkan Runtime Version 1.0.42.1

Video of the Build I downloaded: [here](https://www.youtube.com/watch?v=AaJQHpAxCxQ)

The build itself: [here](https://drive.google.com/file/d/0B_9vQUilzHlNNVdjbmR4Skd0RTA/view?pageId=113881698577188363419)

So Vulkan crashes immediately for me, although it almost loaded once, it doesn't leave a log file, I'll keep on trying though.

As for OpenGL, well I get [this](https://www.youtube.com/watch?v=rj4Sya_75YA)

Basically discoloration and that half screen glitch, up until the mach speed zone where everything looks and works alright save for the frame dip halfway through it. Then after the goal ring, it reverts. It's the same for the others, although I haven't done Radical Train yet, I assume it's the same. I thought it was weird, and heard no mention of it so thought I would just put it here. OpenGL does leave a log file, so I'll include that.
[xenia Sonic 06.txt](https://github.com/xenia-project/game-compatibility/files/1242955/xenia.Sonic.06.txt)

I know OpenGL support is discontinued, just thought I'd include it, honestly if Vulkan would work for me I'd just use that.

I'll probably keep playing around with it, might be better if I built from source myself probably :/

If this is all useless feel free to delete my comment 👍

**Comment by Parovozik** [comment]
@lumo93 try this build https://mega.nz/#!NshUhQLa!MMdm1-0D92G6VyqmxlROZE8zWB3GI8eAAr0Kf_GK-pg
this last sth06 by AllanCat and works is fine for me

**Comment by Parovozik** [comment]
@lumo93 You used fixed cache file for this game or used original image? For current needed replace him.
Path to file: \Sonic_Hedgehog\xenon\archives\cache.arc (If your game as ISO image then you need unpack it, Xenia supported run game directly, there file 'default.xex' in root folder)
fixed 'cache.arc' (https://mega.nz/#!Zow0wS5R!P_lhALa-oRh2OL-mc4xMaZpgHCKYZSOIXzGBeDW5qDc)
This needed because on original cache some stuff generate crashes (antialliasing, shadows...)

**Comment by lumo93** [comment]
@Parovozik I had a cache file, I tried yours, and I also tried without, it seems inconsequential, Vulkan still won't run, and OGL behaves exactly the same way. I did run the game extracted using the xex file. We can rule out cache issues, and build issues. If you have any other ideas I can keep trying. I think we should work on why vulkan won't start for me. I know it starts and immediately crashes, but that's it. I'll keep on trying other stuff. Thanks for helping me with this 👍

**Comment by Parovozik** [comment]
@lumo93 You can look my video record here (https://www.youtube.com/watch?v=bOF_XxOhXXY)

**Comment by Irixion** [comment]
The only reason the original cache crashes is MSAA is not supported on Vulkan just yet. @Parovozik. As for your crashing @lumo93 , attach the vulkan crash log file.

**Comment by lumo93** [comment]
@Irixion I'm attaching the log file, took a while to find for me

[Xenia Sonic 06 Vulkan.txt](https://github.com/xenia-project/game-compatibility/files/1246036/Xenia.Sonic.06.Vulkan.txt)

@Parovozik You got the same card as me, nice, at least I can rule out that

**Comment by lumo93** [comment]
@Irixion and @Parovozik So I realized I was putting the cache ark in the wrong spot, when I corrected it, Vulkan decided to start loading, I'm using the same build as the one in the log I just sent, although I accidentally minimized and it crashed again. 

I had to remake the log file, this one doesn't have the minimize crash but I can try to recreate it if you want.
[Xenia Sonic 06 Vulkan Running.txt](https://github.com/xenia-project/game-compatibility/files/1246146/Xenia.Sonic.06.Vulkan.Running.txt)

Sonics quills are missing in this build still but I'm just glad it works now 👍

**Comment by ItsIggy** [comment]
Something very... unusual has been going on with with my PC regarding emulating this game. The cache file that Allan Cat works sort of. It removes the black bar that consoles half the screen but now I can only see Sonic's eyes and particle effects in gameplay along with some miscellaneous things like water in fountains and people's hair. Ui is fine. But part kept playing just for another minute to do the the first mission of the game(you know the one with the red hoops.) Only to find something very odd when I hit a spring. While falling after hitting the spring the camera angled down enough to show that the level WAS rendering only they seemed to be rendering beneath me, albeit with overlapping issues as well. I want to fix this but don't know how. My specs:CPU Intel core i7 3770 3.4 ghz GPU:AMD r9 290x. I made an account just in hopes of getting this fixed, please help me.

**Comment by Irixion** [comment]
@ItsIggy The cache file only disables MSAA (Which the emulator doesn't yet support), which is why an unmodified game crashes, and comments out the lines that tell the game to calculate and draw the dynamic shadows (which is all of them) for objects and geometry.

AMD cards don't support a needed texture format. Until a workaround is implimented, you're out of luck. Your only bet is to use the deprecated OpenGL backend.

Xenia doesn't have enough contributers to speedily impliment and fix problems, unfortuately. So it's a waiting game.

**Comment by ItsIggy** [comment]
Thank you! Bummer I have to wait for Vulkan, but oh well I have too many games anyways.

**Comment by FreakishDust** [comment]
Hello, with the latest version of the xenia build my Sonic The hedgehog 2006 has incomplete player models as well as major slowdown. Any ideas as to why?

I've linked an image as to show you the incomplete models: https://imgur.com/a/BQWEh

**Comment by Irixion** [comment]
Cool. We know. There’s a workaround that’s been posted in this thread. Spend some time reading it. Or just go play the game on your Xbox 360.

**Comment by FreakishDust** [comment]
but what about my slowdown issue?

**Comment by Irixion** [comment]
You’re either using the deprecated OpenGL backend or have a potato computer. Maybe both. If you want to play this game properly, a console is the only way to currently do so.

**Comment by BateauSD** [comment]
Hello everyone, I have a small problem with the attempts of the launch of Sonic The Hedgehog 2006.
The ISO is started but after 5-6 seconds the picture freezes.
Then I hear only the sounds of the game, but later freeze herself Xenia emulator.
My PC must support VulcanAPI, GTX1050ti+i7 7700. 
What the problem might be?  Tried different Xenia builds, but everything "not responding" on the same place,
![xenia_2017-11-14_03-14-48](https://user-images.githubusercontent.com/13334848/32769686-a766f9b4-c968-11e7-95b8-2ff8db885762.png)

**Comment by RageShin** [comment]
PLS help me.
![2017-12-25](https://user-images.githubusercontent.com/34840356/34342062-006bc1b2-e9b6-11e7-9088-676418c372d7.png)

**Comment by AlexS2412** [comment]
for some unknown reason i cant save in the game and other people can. 
instead of showing this screen : 
![image](https://user-images.githubusercontent.com/14182708/34752844-b5f6ab1e-f582-11e7-95b4-aebb4b989885.png)

it shows this one : 

![image](https://user-images.githubusercontent.com/14182708/34752855-c44da082-f582-11e7-891a-69933fbf8f43.png)

 and since xenia obviously cant sign in it stops me from using a save file to test later portions of the game. does anyone know why this happens or how to fix it?

**Comment by Irixion** [comment]
Copy the save file from your console over.

**Comment by AlexS2412** [comment]
i tried this with a 100% save from the real console. it just ignores it and asks anyway.

**Comment by Irixion** [comment]
Then I’d suggest to make sure you have the save file in its proper location. I’d hat doesn’t work then delete and redone load Xenia, and place it in a folder closer to the C:/ directory rather than say, on your desktop

**Comment by AlexS2412** [comment]
this is the save file i am using. also my xenia folder is already in C;/emulators/ .
[SonicNextSaveData.zip](https://github.com/xenia-project/game-compatibility/files/1617340/SonicNextSaveData.zip)

is there any other way to fix it?

**Comment by Irixion** [comment]
@AlexS2412 Your save file .bin should be in "XENIA\content\534507D6\00000001\SonicNextSaveData.bin"

**Comment by AlexS2412** [comment]
It is. @Irixion

**Comment by AlexS2412** [comment]
Found out its caused by scp server. If its installed,xenia magically cant save. I dont get why it happens but it does.

**Comment by lumo93** [comment]
@AlexS2412 I think it's the way scp server manipulates xinput, which probably affects saves. I know the controller has to have the player one designation or it won't work.

**Comment by AlexS2412** [comment]
I figured out it will work fine as long as you force scp,or whatever output client you are using to make the controller as the 1st controller. It works fine with my ds3 controllers and my switch joycons

**Comment by jpb18** [comment]
Hey there!

Currently I've a problem right after the first cutscene of this game. Once the cutscene ends, Xenia will loose the graphics device and stop rendering the second cutscene: 

![image](https://user-images.githubusercontent.com/11457062/36214934-952f44e0-11a2-11e8-87f4-87f05b19df05.png)

Current hardware:
Intel Core i7-7700HQ
NVIDIA GeForce GTX 1050 4GB
Version of Feb 14 2018.

Also attached is the log file:
[xenia.log](https://github.com/xenia-project/game-compatibility/files/1724756/xenia.log)

**Comment by Dominicmgm** [comment]
“playable with minor glitches”

The whole game on a normal console is a glitch. Awful camera, awful load times, etc.

**Comment by lumo93** [comment]
@jpb18 I'm not sure how much help this will be for your case, I know that my GTX 1050 TI has more recent updates that for whatever reason remove vulkan. I doubt that's your issue, but just in case, check out the [Vulkan Hardware Database](http://vulkan.gpuinfo.org/) and look for your card and operating system, If vulkan was removed I'm not sure how you would even be playing it tbh, but give it a shot. Just look for the latest update on that list, that's the one that has vulkan, it's a bit older for sure, but it's the only way to use Xenia as far as I am aware. (There's opengl but they are doing away with that). Let me know how that works out for you.

**Comment by Razzile** [comment]
@SonicASD that sounds related to this issue https://github.com/benvanik/xenia/issues/801

**Comment by SonicASD** [comment]
@Razzile Makes sense.
@AllanCat Is it alright if you share that unluac fork? I couldn't figure out how to compile the source.

**Comment by eunhon93** [comment]
Why does this game need a Cache? Do other games require it too?

**Comment by Parovozik** [comment]
@eunhon93 There changed some game settings, and this only for Sonic06 (cache file this part of game Sonic 06).

**Comment by DoctorGibuz** [comment]
Ok im having issues, i cant play the game, the menues work but the menu background is black and when i got to episode select or trial the game crashes. I'm using a modified Cache file and running on Vulkan.

**Comment by Bluesfire** [comment]
Been playing through on the latest master build, ran into this issue during Shadow's story, entering Kingdom Valley. Can't continue gameplay. Was able to finish Sonic's story though. Video also shows intermittent pauses in game play, which happens randomly all the time.

https://www.youtube.com/watch?v=3C82j8TxfHQ&feature=youtu.be

**Comment by Irixion** [comment]
@Bluesfire You're supposed to press Y to enter the craft. Some scripts don't execute as they do on hardware for whatever reason. The stutter is just the GPU cache, I don't think Xenia stores them anywhere so it has to compile them every time. (Someone correct me if I'm wrong)

@DoctorGibuz Sounds like you're using an AMD card. Or a crappy cache file. Neither are going to work.

**Comment by Bluesfire** [comment]
Ah, awesome! Thanks for letting me know. I'm using a GTX 1070 TI, I've seen people with lower graphics card play without the stutter. but I can't find any explanation of how to get it like that.

**Comment by MrMrMANGOMILK** [comment]
@DoctorGibuz Make sure you have the right cache file, then? I use an AMD card and the build linked in @Parovozik 's video works just fine for me.

Also, does anyone know _why_ the shadows don't work? Is it like the AA and Xenia just doesn't support it yet?

**Comment by Irixion** [comment]
@MrMrMANGOMILK Shadows work...sort of. The game uses real time shadows via Cascaded Shadow Maps (CSM) for everything including level geometry. If the game tries to draw shadows, it ends up covering the wrong parts in shadows, making it look dark. Some parts of geometry will be in the light, while others will be in the dark. This is probably due to Xenia not being able to properly calculate where to draw the shadow maps.

As far as AA goes, Xenia doesn't support it at an emulation level. If you try to start the game with AA enabled, Xenia will crash.

The cache file specifies what parameters the game will use when initializing its rendering pipeline. Shadow map resolution, distance as well as the type of SMAA (x2 vs x4, etc), each scene will use. The edit basically disables both as soon as the game starts, ignoring all future calls for AA or CSM.

**Comment by Irixion** [comment]
Sorry for the double post. But the latest commit #9a158963, introduces some...anomalies. @DrChat.

Since older commits crash, I'm assuming because of Vulkan being updated on the driver side, I can't run the older versions, but, the commit introduces some odd stippling.

![image](https://user-images.githubusercontent.com/26639385/39669517-0624bee8-50bc-11e8-8f7e-7dc90c124366.png)
 I'll do more testing tomorrow.

**Comment by Irixion** [comment]
Hey all. So the stippling has been fixed. However, there's some outlines around some textures which shouldn't be there.

![image](https://user-images.githubusercontent.com/26639385/40275523-99e748ae-5bbf-11e8-9686-453e61a295b3.png)

Black lines on the splines?

**Comment by gibbed** [comment]
Can you highlight what you're referring to in the image?

**Comment by Irixion** [comment]
![image](https://user-images.githubusercontent.com/26639385/40280902-db7bd7cc-5c27-11e8-980f-e7f58c567904.png)

Here's a clearer shot. That dark line between the two hues of blue shouldn't be there. In the above image that I posted, on the spines, there are two lines above his hands.

**Comment by gibbed** [comment]
Ignoring the line, are the colors supposed to be drastically different like that?

**Comment by Irixion** [comment]
Well, that specific shot, no. Reflections don't work properly yet. However that dark space is new. With the last 5 or so commits, performance has severely tanked, and the minimap shows a garbled mess. So some regression.

**Comment by gibbed** [comment]
"Recent changes in Xenia cause a lot of problems:"

This is the wrong way to approach this. Xenia is a **_work in progress_**. There will be times problems crop up. That doesn't negate the value of the improvements that have been made.

1) You can optionally disable the timer if it's causing an issue.
2) Yes, known issue.
3) Note how the commit message is *workaround*.

**Comment by Realex-fire** [comment]
I don't urge to roll away changes. I have listed problems that I have noticed.

**Comment by gibbed** [comment]
@Realex-fire Sorry, I meant "aware" not "away". But that's fine. I just wanted to make it clear that sort of tone in your original post doesn't really help.

**Comment by Irixion** [comment]
Xenia just dies now while trying to play the SEGA .wmv.

**Comment by Irixion** [comment]
So, I have some good news. Shadows work now!...sort of.

![image](https://user-images.githubusercontent.com/26639385/41490611-dfb33e16-70c2-11e8-8831-f652c2f818db.png)

They're still not properly drawn, and the game sits in the dark most of the time, but it's something.

**Comment by Irixion** [comment]
I'll take some screenies later, but the CubeMap commit fixed the water, as well as the chrome spheres in Aquatic base. It also fixed pretty much everything else that uses a cube map. (Crisis City buildings, Windows, Sonic's shoes, etc.)

**Comment by MrMrMANGOMILK** [comment]
I assume that's with a different version of the cache? The AA stuff still isn't supported so I assume all this one does is add shadows back in.

Also some recent commit (not sure which) makes the XBLA demo crash the emu now. No clue why, as it was at least rendering the scene on earlier builds (albeit wrong like how it was before AMD cards got fixed)

**Comment by Irixion** [comment]
@MrMrMANGOMILK I was under the assumption that AMD cards were never "fixed". This cache is my version, and really all it does is remove the AA checks. The rest is original. As far as the Demo goes, it still functions fine on my end.

**Comment by MrMrMANGOMILK** [comment]
@Irixion The build @Parovozik linked back in February was the first time the layering issues got fixed on my AMD card. Maybe that wasn't actually intentional, but it's how it's turned out. That build ran the demo with the same issues as AMD cards were still exhibiting, but now it crashes. (the emu itself - it doesn't lead to the "Client has crashed" message")

Also for some reason I thought the current cache disables both AA and shadows, sorry for the misunderstanding

**Comment by Irixion** [comment]
@MrMrMANGOMILK Afaik, AMD cards don't support a texture format, which is why they don't really work. There's some trickery that needs to be implemented. Or something. Someone else may explain it better than I can.

As far as caches go, there's the "first" one that simply switched the game's rendering to one used for internal testing (disables all the graphical effects, really), the wild one on the internet which does some strange butchery to disable things, and the one that @AllanCat released. All his does is comment out the lines that initialize AA and CSMs.

My cache, the one I made for myself, just disables AA.

**Comment by Irixion** [comment]
The last few commits broke the cube maps again, somehow :S

**Comment by Geroyuni** [comment]
Hello, I'm using this [cache.arc by allancat](https://drive.google.com/file/d/0B_9vQUilzHlNS2JMS3BOd3pFMXM/view) and the latest release of xenia, but I'm only getting locked 30fps after loading into soleanna. Can I do anything better? Tried some builds like sth06 from allan but [it gives me the vulkan error](https://i.imgur.com/66uC61V.png). Using i5-6600, GTX 1070.

![image](https://user-images.githubusercontent.com/6061850/42423732-cb59b2c2-82d5-11e8-9000-47359425d834.png)

**Comment by FateForWindows** [comment]
Recent commits caused major performance drops in an attempt to work around a major VRAM leak issue which has affected this game as well as many more. My CPU is weak too (i7-4710MQ overclocked to 3.3 GHz) so you're not the only one affected by this. You can either use this [custom build](https://ci.appveyor.com/api/buildjobs/v3mqwtse0ig2es3y/artifacts/xenia-master.zip) of Xenia (current master without the workaround implemented) or use [this fix](https://www.reddit.com/r/rpcs3/comments/7p33t1/rpcs3_broken_with_latest_nvidia_driver_39065/dsewfbr/) for the Vulkan error.

Note that the custom build still suffers from the VRAM leak and will eventually experience an overflow. To get around that, hit Clear Cache. The game will eventually lose the graphics card anyway.

**Comment by Parovozik** [comment]
@Geroyuni try it build. I think it b est for Sonic 06 https://drive.google.com/open?id=14DUn49yQCeKwcnn7LS225VD8SWmw2PXB

**Comment by FateForWindows** [comment]
Just found your VRAM leak fix @Parovozik. I implemented it into the Master branch and made this. https://ci.appveyor.com/api/buildjobs/6541qtkoytpea5yo/artifacts/xenia-master.zip

Probably not the best for 06 but eh, it works.

**Comment by FateForWindows** [comment]
There's still issues with the game drawing shadows, but otherwise this is in a playable state. It's also missing the tech-middleware-criware label.

**Comment by Geroyuni** [comment]
Oh yeah definitely. There's also the purple weirdness on fade in/out and in the last episode, at least for me

**Comment by MirrorOfDespair** [comment]
Hello there. I used the two builds mentioned above and they worked nicely for me. However, the game decides to run at 2 FPS or so whenever I fullscreen it. Nothing changes when I bring the window to normal size again. Does anyone know why this happens and how to fix it? Using i7-4720 and GTX 950M with 8GBs of RAM.

**Comment by Ibrahim9999** [comment]
Hello, I'm new to the mix so forgive if I miss something obvious.

I'm encountering a black screen when Omega ever appears on the screen, however all the words from subtitles and indicators show (but they're blurry, even the pause menu). Otherwise, the game runs smoothly at 60 fps and no errors at all, but the Omega issue is stopping me from completing the game. Is this a shader cache issue, vulkan issue, or hardware issue? I'm pretty sure I have all the updated drivers, so I don't think it's my pc that's the problem. Thank you for your time!

![image](https://user-images.githubusercontent.com/18268971/45540491-6ff99980-b7c1-11e8-8c32-c3935afe0660.png)

**Comment by DRIVANnega** [comment]
i gonna off topic to unrelated game to 2 Crash Bandicoot games still have problems with character model and audio issues on the game...while this game works flawless besides some shadow levels hand-gliders not function right still...so i wonder when developers fix this to mainline trunk

**Comment by Razorak** [comment]
@Ibraham9999 I have the same issue as you. It's making the Last Chapter pretty much unplayable for me.

**Comment by Irixion** [comment]
You're not supposed to be able to play the game. OpenGL is deprecated, and, someone correct me if I'm wrong, but pretty soon Vulkan will be as well. Direct X 12 will eventually be the new back end, As it stands now, the game, along with its demo, crash at the main menu. There's nothing to "fix". It just isn't anywhere near finished. You're trying to use a half built bridge to get across. It's just not going to work.

**Comment by gibbed** [comment]
There are no current plans to deprecate Vulkan. The situation is that the only active development as of this moment is Triangle's D3D12 branch.

**Comment by MrMrMANGOMILK** [comment]
...I'm not entirely sure what you mean by this. The game has worked in Vulkan (albeit with broken features) since at least February (we've been hacking the game to allow it to work).

Also a side note: the September 10 build made the XBLA demo crash Windows instead of just the emulator. Again, I'm on an AND card. (Hoping AMD's implementation of an apparent unsupported texture format works on DX12. The game only uses DDS oddly enough so I'm not sure what was being referenced but whatever)

**Comment by Ibrahim9999** [comment]
What do you mean that the game and its demo all crash on startup? This only
happens with my OpenGL version of the emulator, the Vulkan one works fine
up until when Omega appears on the screen.

**Comment by Irixion** [comment]
> ...I'm not entirely sure what you mean by this. The game has worked in Vulkan (albeit with broken features) since at least February (we've been hacking the game to allow it to work).
> 
> Also a side note: the September 10 build made the XBLA demo crash Windows instead of just the emulator. Again, I'm on an AMD card. (Hoping AMD's implementation of an apparent unsupported texture format works on DX12. The game only uses DDS oddly enough so I'm not sure what was being referenced but whatever)

Uh, I meant on the DX 12 back end. WMV files don't like DX 12 yet, and then it decides to crash once any 3D elements try to get rendered.

As far as the emulator crashing Windows, I would say it's AMD's less than stellar driver. But, I think the unsupported texture format is where DX 12 would come in anyway.

**Comment by MrMrMANGOMILK** [comment]
So DX12 has had a few improvements recently. The WMVs don't break anymore, and you can actually get into gameplay. The image is stretched vertically, though, and a portion goes off the top of the frame. Also, there's quite a bit of slowdown, and some visual effects break. XBLA demo has none of these issues fortunately (though it crashes after the results screen when it's supposed to show a promotional image).

AMD also has an issue where certain animated models explode, which happens in Sonic Unleashed too (though not nearly to the extent it does in that game).

**Comment by Parovozik** [comment]
@MrMrMANGOMILK there incorrect MSAA render

**Comment by Irixion** [comment]
There's something peculiar happening. There seems to be texture corruption happening here. In some scenes, for example, this smoke effect works, and the same effect, in others, it looks off. In addition, things like the HUD go wonky as well. Here's some photos to demonstrate what's going on.

![image](https://user-images.githubusercontent.com/26639385/46639384-9e099980-cb33-11e8-9d9e-1433f0ddca0c.png)



![image](https://user-images.githubusercontent.com/26639385/46639436-0193c700-cb34-11e8-92f1-b7d15cea6d96.png)


![image](https://user-images.githubusercontent.com/26639385/46639239-fd1ade80-cb32-11e8-89b7-77f26a2d5cd2.png)

**Comment by FateForWindows** [comment]
@Irixion Are you using Vulkan or DX12? If you're using DX12 it may be a VRAM issue.

**Comment by slashiee** [comment]
Can't access my save file anymore with the latest build from the d3d12 branch
![2018-11-20_19-57-14](https://user-images.githubusercontent.com/15317421/48818210-00db7c80-ecff-11e8-9c95-094a54b171f7.png)

**Comment by RonDaBlue** [comment]
> Can't access my save file anymore with the latest build from the d3d12 branch
> ![2018-11-20_19-57-14](https://user-images.githubusercontent.com/15317421/48818210-00db7c80-ecff-11e8-9c95-094a54b171f7.png)

https://www.xpgamesaves.com/resources/sonic-the-hedgehog-2006.4672/ Extract that save file using Velocity (A program) and then make "content" folder in your xenia... and then.. \534507D6\00000001\SonicNextSaveData.bin  yea... also those are the folders... also that last one (SonicNextSaveData.bin) you need to make that a folder too, and inside put the save (extracted using velocity) if you didn't fully understand (since i suck at explaining) Here's my discord: RonDaBlue#4310

**Comment by FateForWindows** [comment]
> Can't access my save file anymore with the latest build from the d3d12 branch
> ![2018-11-20_19-57-14](https://user-images.githubusercontent.com/15317421/48818210-00db7c80-ecff-11e8-9c95-094a54b171f7.png)

Put an empty file named "portable.txt" in the Xenia folder.

**Comment by slashiee** [comment]
I'm aware of all the save stuff, please stop replying to the post.

**Comment by UnrealNinjaMark** [comment]
Hey Guys.
I tried to use the DXD12 Executable for running Sonic 2006.
Everything seems to work well, but when I play first cutscene, audio become out of sync and reproduce things very earlier than that happens to video!
Can someone help me, please?

**Comment by Paniio123** [comment]
if only someone could make a modified cache to disable shadows and msaa for the newest dx12 release, it works flawlessly with the default cache in stages and city albeit with weird colors when you jump or are in a scripted scene.. using the vulkan cache works 50/50 (artifacting like in the pic above my comment)

**Comment by UnrealNinjaMark** [comment]
But when I try to use Vulkan version, game crashes the emulator.
And using ST06 Vulkan version, it stops working when I try to send an input.
Last, but not least, On my PC the DX12 version is also a bit slower than
original. And there is audio sync problem.
Thanks for reading.

**Comment by UnrealNinjaMark** [comment]
Ok.
My PC is not very powerful.
Intel 4200U i5
AMD Radeon R5 M230 (DX12 support) with 2GB VRAM
12 GB RAM
Windows 10 Home 64bit
But it's ok. WiiU Games sometime run smooth with Cemu Emulator, but Isn't a
monster.
Thanks Anyway.

Il giorno mer 9 gen 2019, 23:43 FateForWindows <notifications@github.com>
ha scritto:

**Comment by UnrealNinjaMark** [comment]
Ok.
My PC is not very powerful.
Intel 4200U i5
AMD Radeon R5 M230 (DX12 support) with 2GB VRAM
12 GB RAM
Windows 10 Home 64bit
But it's ok. WiiU Games sometime run smooth with Cemu Emulator, but Isn't a
monster.
Thanks Anyway.

**Comment by Paniio123** [comment]
> Ok. My PC is not very powerful. Intel 4200U i5 AMD Radeon R5 M230 (DX12 support) with 2GB VRAM 12 GB RAM Windows 10 Home 64bit But it's ok. WiiU Games sometime run smooth with Cemu Emulator, but Isn't a monster. Thanks Anyway. And... Yes, my graphics driver are up to date, and I tried to use shader caches.

https://www.youtube.com/watch?v=vQwZ3XlxZGY&t check the description and download his XENIA 1.06-ML-Custom-Build and cache v3

**Comment by UnrealNinjaMark** [comment]
I'll check up your link as soon as I can!
Thanks a Lot!!

**Comment by UnrealNinjaMark** [comment]
Hey
Your build works perfect!!
Thanks!!!😂

Il giorno ven 11 gen 2019, 04:17 Paniio123 <notifications@github.com> ha
scritto:

**Comment by Paniio123** [comment]
jump ? press A on your controller lol.. audio desync is the emulators fault so nothing can be done about that atm

**Comment by NimbusSkye** [comment]
![screenshot 364](https://user-images.githubusercontent.com/46655325/51089592-cf4ec280-173d-11e9-8585-972a374e90af.png)

Shadow's Kingdom Valley will always begin in this situation. Progress is impossible because I can't equip the glider at all, even when clicking the Y button (which usually allows you to take control of a vehicle). Resetting has no effect, and I am effectively stuck at this point in Shadow's story.

Here are the issues with Radical Train's Mach Speed section in Sonic's story. The extreme visual glitches render it almost unplayable. This recording is from January 1's build, but these issues are still present in the current D3D12 build.

https://www.youtube.com/watch?v=K2FRI4d9woM

**Comment by Irixion** [comment]
I don't get any visual artifacts like that. On a 1080

**Comment by Exayne** [comment]
@NimbusSkye Yea it certainly was interesting, however a restart fixed it.

**Comment by FateForWindows** [comment]
@NimbusSkye Graphical glitches of that type are pretty common with DX12. They can happen in other areas of the game too and other games suffer from the same issue. Also, I don't normally have the glider issue on either Vulkan or DX12 (sprung up twice total), though it has a random chance of happening with Xenia. Both times it happened I was just able to press Y, though.

**Comment by NimbusSkye** [comment]
An update to my previous post, it seems that the glider issue eventually fixed itself and I was able to progress past the beginning of Shadow's Kingdom Valley. Still, this issue was never seen on the original console. It may be exclusive to the D3D12 build, since I haven't been using Vulkan since I started playing this game.

The glitches in Radical Train are definitely still a huge problem and are impossible to avoid. The most recent D3D12 build still has those issues.

**Comment by FateForWindows** [comment]
Forgot to clarify in my last post: it can indeed happen in Vulkan. That's how it happened both times for me.

**Comment by NimbusSkye** [comment]
Silver's Tropical Jungle is plagued with extreme slowdown and frame rate drops, but everything else seems to be fine. Tropical Jungle is fine for both Sonic and Shadow's story.

i7-8750H 8GB RAM, GTX 1060 6GB VRAM

**Comment by NimbusSkye** [comment]
Actually scratch that, the entirety of Silver's story is horrible. The only stages that ran decently were Crisis City and Dusty Desert, every other level is constantly plagued with extreme slowdown. DX12 build with the Vulkan patch. Vulkan runs even worse, barely hitting 30fps in-game.

**Comment by NimbusSkye** [comment]
I should add an update for the latest DX12 build from April 11; it is a drastic improvement over previous builds. The game's graphics seem to be somewhat upscaled by default but there is also much less slowdown and glitches than before. I still have to play through Silver's stages to give a full report, but for now I can say that the devs have done a really nice job.

**Comment by NimbusSkye** [comment]
![Screenshot (468)](https://user-images.githubusercontent.com/46655325/56087551-7b866f00-5e3b-11e9-8c46-232811585ca3.png)
Here's an example of the texture corruptions that appear on NVidia GPUs. 

The other major example is the mach speed section in Sonic's Wave Ocean, where the rock pillars display a conglomeration of random colors. Sonic's Radical Train is still nearly unplayable due to the sheer amount of texture corruptions in the mach speed section.

That being said, Silver's levels are all playable now. The extreme slowdowns are mostly gone.

**Comment by MuhammadIlaahi** [comment]
Hi! I am having similar issue here. Although the issue is moreover the camera is completely wrong so its hard to play. Any helpful tips?
![image](https://user-images.githubusercontent.com/36990948/56297288-60b04500-6130-11e9-8201-7e8689ffd6ea.png)

**Comment by MANGOM1LK** [comment]
Update your Xenia version my guy. That issue has long since been fixed.

**Comment by MuhammadIlaahi** [comment]
> Update your Xenia version my guy. That issue has long since been fixed.

Update it how? I am sorry. I am new to Xenia :3

**Comment by NimbusSkye** [comment]
> Update it how? I am sorry. I am new to Xenia :3 And update it to what?
https://xenia.jp/download/
Seriously, it's not that hard to perform a quick Google search.

**Comment by MuhammadIlaahi** [comment]
> > Update it how? I am sorry. I am new to Xenia :3 And update it to what?
> > https://xenia.jp/download/
> > >
> 
> Seriously, it's not that hard to perform a quick Google search.

I asked because I've downloaded several Xenia builds before and none of them seem to work as this one I have now. So that's why I am asking specifically which one because I don't want to run a build which either crashes or cannot be loaded.

**Comment by MANGOM1LK** [comment]
The game loads in every build newer than the one you are using, but you need to get the Configuration: Release build (if you are using Appveyor), everything else breaks afaik

**Comment by MuhammadIlaahi** [comment]
> > > Update it how? I am sorry. I am new to Xenia :3 And update it to what?
> > > https://xenia.jp/download/
> > > >
> > 
> > 
> > Seriously, it's not that hard to perform a quick Google search.
> 
> I asked because I've downloaded several Xenia builds before and none of them seem to work as this one I have now. So that's why I am asking specifically which one because I don't want to run a build which either crashes or cannot be loaded.

Thank you, the d3d12 (D3D12) build works great! Only issue is that the game runs a bit slow at certain frames. I had this issue before when I played the game 1.5 years ago, but if I opened and exited the game enough times it would eventually play smoothly.

**Comment by NimbusSkye** [comment]
>Thank you, the d3d12 (D3D12) build works great! Only issue is that the game runs a bit slow at certain frames. I had this issue before when I played the game 1.5 years ago, but if I opened and exited the game enough times it would eventually play smoothly.
>>
That is normal, the emulator is nowhere near finished. Even a high-end gaming PC like mine will have issues. Would you mind listing your specs?

**Comment by dehdos** [comment]
I have an issue where every time omega appears, during the shadow episode i get a black screen, doesnt matter if its a cutscene or gameplay. please help?

**Comment by FateForWindows** [comment]
> I have an issue where every time omega appears, during the shadow episode i get a black screen, doesnt matter if its a cutscene or gameplay. please help?

Omega doesn't display properly with Vulkan. You'll need to use a DirectX 12 build or [this custom build](https://github.com/lost-legacy-team/LoS-Miscellaneous/raw/master/Emulators/Performance/Xenia%201.05-MLBS%20(2314f25f)%20[22nd%20June%202018].exe).

**Comment by MuhammadIlaahi** [comment]
> > Thank you, the d3d12 (D3D12) build works great! Only issue is that the game runs a bit slow at certain frames. I had this issue before when I played the game 1.5 years ago, but if I opened and exited the game enough times it would eventually play smoothly.
> > >
> 
> That is normal, the emulator is nowhere near finished. Even a high-end gaming PC like mine will have issues. Would you mind listing your specs?

Sorry for the late response. These are my specs.

Processor Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
RAM 16 GB
Video Card NVIDIA GeForce GTX 1060 3GB

**Comment by dehdos** [comment]
> > I have an issue where every time omega appears, during the shadow episode i get a black screen, doesnt matter if its a cutscene or gameplay. please help?
> 
> Omega doesn't display properly with most newer Vulkan builds. You'll need to use a [DirectX 12 build](https://ci.appveyor.com/project/benvanik/xenia/history) (look for the newest one with the "d3d12" branch instead of "master") or [this custom Vulkan build](https://github.com/lost-legacy-team/LoS-Miscellaneous/raw/master/Emulators/Performance/Xenia%201.05-MLBS%20(2314f25f)%20%5B22nd%20June%202018%5D.exe).

but now the problem is that my saved game is gone when i am using this custom vulkan build

**Comment by FateForWindows** [comment]
> > > I have an issue where every time omega appears, during the shadow episode i get a black screen, doesnt matter if its a cutscene or gameplay. please help?
> > 
> > 
> > Omega doesn't display properly with most newer Vulkan builds. You'll need to use a [DirectX 12 build](https://ci.appveyor.com/project/benvanik/xenia/history) (look for the newest one with the "d3d12" branch instead of "master") or [this custom Vulkan build](https://github.com/lost-legacy-team/LoS-Miscellaneous/raw/master/Emulators/Performance/Xenia%201.05-MLBS%20(2314f25f)%20%5B22nd%20June%202018%5D.exe).
> 
> but now the problem is that my saved game is gone when i am using this custom vulkan build

To fix this iirc move the "content" folder from C:\Users\desko\Documents\Xenia to whereever you saved the custom build, then create a file named portable.txt so that other newer versions of Xenia in that folder will use that save.

**Comment by Al-AmeenAdewunmi** [comment]
Any way I can get this to 60FPS? It's stuck at a measly 20 at best.

Processor: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 CPUs), ~2.6GHz
Memory: 8192MB RAM
Available OS Memory: 8056MB RAM
Card name: Intel(R) HD Graphics 520
Manufacturer: Intel Corporation
Chip type: Intel(R) HD Graphics Family

![Screenshot (240)](https://user-images.githubusercontent.com/53586162/62372866-735c5780-b530-11e9-9044-5285894fb04f.png)

**Comment by FateForWindows** [comment]
@Al-AmeenAdewunmi That's normal for a laptop (assuming that based off of the CPU model) with those specs. You'll need a decent GPU in order to get 60FPS and Intel's integrated GPUs won't be able to get good performance even in the best scenarios.

**Comment by KBouder** [comment]
I've been having some texture glitches ever since a few updates ago. This isn't something related to this game in particular, but actually affects almost every game that I've tested besides the Geometry Wars 2 Demo. This game was just the only one with multiple examples in the menu. Issue is present in both DirectX and Vulkan.
![image](https://user-images.githubusercontent.com/11525691/65158394-38d74d00-da00-11e9-91e1-399b09f625e7.png)
![image](https://user-images.githubusercontent.com/11525691/65158412-47256900-da00-11e9-887a-f3b7035cca73.png)

This isn't an issue that I've seen anyone else reporting, so I'm not sure what makes my testing environment different from others who have the same/similar specs.

--Specs--
Ryzen 7 2700X
NVidia GeForce RTX 2070 (latest drivers as of today)
16GB Ram

**Comment by slashiee** [comment]
RTX issue, https://github.com/xenia-project/xenia/issues/1475

**Comment by KBouder** [comment]
Thank you for pointing that out Slashiee, I didn't realize it was an RTX specific issue (although every emulator issue I've had thus far has been due to RTX). I should have learned by now 😛

**Comment by Margen67** [comment]
@KBouder Retest with driver 440.97

**Comment by WaggishOhio383** [comment]
I've been making good progress through the game without many glitches. The few that occurred weren't to the point that the game was unplayable. However, near the start of Shadow's story, I've encountered a glitch that makes the level impossible to complete. The level starts you out on a glider that you use to navigate a decent portion of the stage. However, instead of spawning me riding the glider, I start the level standing on top of the glider, which isn't moving, with no way to ride the glider and advance in the stage. I've attached a screenshot below to show what I mean:

![Screenshot (73)](https://user-images.githubusercontent.com/71992312/94378527-500f4700-00f8-11eb-842f-63b19424c802.png)

Here's a clip of what is supposed to happen: https://youtu.be/wL0TSwXfx0M?t=8473
(If the URL doesn't work properly, the section starts at 2:21:13)

Specs of my computer below in case that could be contributing to the problem:
- Ryzen 7 2700X
- AMD Radeon RX 590
- Crucial Ballistix 16GB DDR4 3200

**Comment by strangermoon** [comment]
demo works ok without slows. sometimes crash when too many falling.
![1](https://user-images.githubusercontent.com/42394165/115971922-084c8300-a554-11eb-961c-848410d2d283.png)

**Comment by Mafiu0** [comment]
Game runs perfectly but there are a few slowdowns in Soleanna and Kingdom Valley. I have checked my CPU utilisation and I do no think it's insufficient (it's around 40%). 

Are there any settings that can improve these slowdowns?

**Comment by AbrarsHub** [comment]
Does Sonic 06 work on an Intel HD 520? with a specific CPU of a i7-6500U?

**Comment by lipe993** [comment]
I have the same problem as @Deniztendo638, the music goes fine, but the game runs in 20ish fps and 1 second of input delay, I don't know if the problem is my computer.
```
Motherboard: Asus TUF GAMING B550M-PLUS
CPU: AMD Ryzen 5 5600G
GPU: none, I use integrated graphics
Ram: 8gb
```

**Comment by Megasonic999** [comment]
It works just fine for me, it just has minor graphic glitches that can be fixed by pressing f5.

**Comment by ARONAR1** [comment]
Xenia Team, please change the status of the game to "Playable". Works great from start to finish.

**Comment by SpareEnderboy** [comment]
if there was an fps counter my pc would need to measure sonic 06 in seconds per frame
(dell optiplex 3080, 16gb ram)

**Comment by ConnorStocky17** [comment]
First game i've tried. Game runs absolutely fine, just have a slight issue with a delay in sound input. Cinematics seem to be okay, just delays during gameplay.

12th Gen Intel(R) Core(TM) i5-12400F
32gb RAM

**Comment by eunhon93** [comment]
just play the game with the fan pc port

**Comment by Pipi86** [comment]
> First game i've tried. Game runs absolutely fine, just have a slight issue with a delay in sound input. Cinematics seem to be okay, just delays during gameplay.
> 
> 12th Gen Intel(R) Core(TM) i5-12400F 32gb RAM

Just open the Xenia config file, and change the cvar named "apu_max_queued_frames" from the default 64 to 32, so it should like this:
apu_max_queued_frames = 32

that number helped me in every game i've tried with xenia without any side effect.

**Comment by SkullGrunt128** [comment]
manage to get the game running fine, missing some weird textures here and there. but this happend during the final boss. cant see anything aside sonic eyes.
![image](https://github.com/xenia-project/game-compatibility/assets/167914057/b260c48d-9173-44c6-b18d-eeb449cac789)

**Comment by AVoidKnight** [comment]
changing to direct3d12 fixes this problem
![image](https://github.com/xenia-project/game-compatibility/assets/136589540/9db6766d-3fe3-4b36-b2b8-e8c61c4f6036)

**Comment by shrimpjola** [comment]
how do you save progress? i press sign in and it doesn't do anything it will only let me continue without saving :(

**Comment by NaturalHarmonia** [comment]
Game is mostly playable but when doing the White Acropolis stage and switching from Rouge back to Shadow the ground disappeared. Also, when first playing the stage with Shadow some of the walls were colored weirdly.

**Comment by Gxbrixl564** [comment]
how to save files
cant sign in so i cant save
