### ISSUE TITLE
4B4E0823 - Silent Hill: Downpour

### ISSUE THREAD

**Issue by Ichigo14** [xenia-project/game-compatibility#301]
[Xbox Marketplace](http://marketplace.xbox.com/en-US/Product/Silent-Hill-Downpour/66acd000-77fe-1000-9115-d8024b4e0823)

Nothing happens, black screen

**Comment by TAMPIM** [comment]
Black screen

**Comment by elfogames** [comment]
# Update

Still Black Screen

## Log:
 https://gist.github.com/elfogames/16d11c3261a7a192f53ec5edc1d0bb07

**Comment by josebraund** [comment]
Black Screen

**Comment by Rutjan666** [comment]
Game is playable with [Unofficial Xenia-Custom 1.11i FullPack (Sep28.2019)](https://www.youtube.com/watch?v=WOeTADjEpsc&t=157s).

Performance is great, game supports unlocked fps, some stuttering when many things happen on screen, but other than that, pretty good (even 5.1 surround sound).

Only issue happens during the Centennial Bulding part: When I go past the vault room, then room 208, the emulator constantly force-closes when I step into the main hall. I tried going around the issue by stepping into the vault first, watch the cutscene then on to the main hallo but it doesn't work and Xenia still force closes.

**Comment by Margen67** [comment]
@Rutjan666 Results not from master aren't allowed here.

**Comment by Rutjan666** [comment]
> @Rutjan666 Results not from master aren't allowed here.

Woopsy my bad!

Apparently, master build available [here](https://ci.appveyor.com/project/benvanik/xenia/builds/33255487/job/au1cqo24o350m15d/artifacts) makes the game playable too.

**Comment by Etokapa** [comment]
Tested on https://github.com/xenia-project/xenia/commit/18031a8f6dc2dc52692764c0647b102de4e81d6c

Stabbed a dude, went to prison, rode a bus, helped a cop, powered a tram, got stuck trying to ride it. 62FPS with vsync off and shaders cached. Saves work.

• Text on loading screens can get corrupted, but can be fixed with F5.

![sh (1)](https://user-images.githubusercontent.com/31154606/94347665-c417f500-fffb-11ea-88d8-6bf63b0f8af9.png)
![sh (2)](https://user-images.githubusercontent.com/31154606/94347672-cbd79980-fffb-11ea-8443-e555554518a8.png)
![sh (3)](https://user-images.githubusercontent.com/31154606/94347678-d1cd7a80-fffb-11ea-964d-918efae300f6.png)
![sh (4)](https://user-images.githubusercontent.com/31154606/94347682-d6922e80-fffb-11ea-88b8-42ce349d1bd4.png)
![sh (5)](https://user-images.githubusercontent.com/31154606/94347683-db56e280-fffb-11ea-939e-d3bf0dc84ae0.png)
![sh (6)](https://user-images.githubusercontent.com/31154606/94347688-e1e55a00-fffb-11ea-9e9d-b3d06c9b4de5.png)
![sh (7)](https://user-images.githubusercontent.com/31154606/94347690-e6117780-fffb-11ea-9ba5-e44e84866db8.png)
![sh (8)](https://user-images.githubusercontent.com/31154606/94347691-e873d180-fffb-11ea-9ac8-e1fea50bf978.png)
![sh (9)](https://user-images.githubusercontent.com/31154606/94347692-ec075880-fffb-11ea-86cc-a8e134c78544.png)
![sh (10)](https://user-images.githubusercontent.com/31154606/94347694-ef9adf80-fffb-11ea-9527-b661c9d6f0fd.png)

[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5287142/xenia.zip)

state-gameplay | gpu-drawing-corrupt

**Comment by Falyandar** [comment]
i have a water issue how to fix? 
![84516ea4de3a19629a96c4682c7c0f84](https://user-images.githubusercontent.com/73209396/96672411-d569ce00-1329-11eb-9db7-3703881539a4.jpg) also here is my log file 
[xenia.zip](https://github.com/xenia-project/game-compatibility/files/5413212/xenia.zip) im also running the latest version of xenia, my game runs really good its just that is a little annoying

**Comment by Chloroshi** [comment]
> Apparently, latest Jun 7 master build makes the game playable too, but the emulator crashes when entering the main hall after room 208 in the Centennial Building.

I confirm that this still happens with the latest build as of March 2021. The emulator crashes completely during the autosave while entering the main hall in the Centennial Building, coming from room 208. It is not possible to progress in the game.

Is there any additional info that I can provide to help with this?

**Comment by Rutjan666** [comment]
I think one can only try every new build release...

**Comment by TAMPIM** [comment]
I´m aware of this crash , long time ago i was trying to complete this game on my PC , due to this crash i couldnt : / , if theres a fix post it here please

**Comment by bomabomaboma** [comment]
> I attempted to "bypass" the normal progress of the game by entering the vault first (had to find the combination online...), let the cutscene play, but the game still crashes at the same time after room 208.
> 
> I think one can only try every new build release...

If anybody has a save file from right before the autosave crash, please message me on Xenia's discord, my handle is bomayeknee

**Comment by BM-Hicham19** [comment]
i realy want to play this game but what do i need to play it ????
system requirements ?????

**Comment by TAMPIM** [comment]
> i realy want to play this game but what do i need to play it ???? system requirements ?????

OS: Windows 10 64-bit.
CPU: Any 4th-gen Intel processor capable of AVX2 or newer. Ryzen 5 or above
GPU: Any capable of Direct3D 12's Rasterizer-Ordered Views. (Nvidia GeForce GTX 950 or better, GTX 965M for laptops. Integrated is too slow to be usable. AMD supports it with Radeon Vega but has driver issues.)
RAM: 6 GB or more.

I`ve played on i5 7400 + gtx 970 and 1070 , runs ok , its a long time though i gave up after this crash in main hall, since i couldnt finish the game

**Comment by Chloroshi** [comment]
> i realy want to play this game but what do i need to play it ???? system requirements ?????

You're in for a disappointment because as you an see discussed in a few comments above, this game crashes at a specific point and there's no way to avoid it. It seems that nobody ever completed this game and to this date the problem still hasn't been fixed, or even properly looked into.

But let us know if you have better luck.

**Comment by reikohinomoto** [comment]
Game seems to be playable past the original crash point now (Feb 17 2022 build), however frequently crashes when trying to create save data any time past that. It may be possible to finish the game now, but the shutdowns are a major inconvenience to say the least.

**Comment by reikohinomoto** [comment]
> 
> Hi, I just tested it, I'm still getting the crash at the usual spot.
> 
> Did you manage to get past it?
> 
> Do you have any special settings in Xenia?

Hey. I managed to get past it, yes, however I do not have anything special on my Xenia. I noticed there seems to be a 50/50 chance the game is gonna crash whenever it saves when you go into the Centennial Building, so maybe I just got lucky.

> 
> How far did you go ?

Not very. I got dragged to the Otherworld and the game kept crashing whenever I reached a checkpoint. I'm gonna test it more later, see if a new (constant) crash happens somewhere or if the issue is indeed only in the Centennial Building.

**Comment by Chloroshi** [comment]
> Game seems to be playable past the original crash point now (Feb 17 2022 build), however frequently crashes when trying to create save data any time past that. It may be possible to finish the game now, but the shutdowns are a major inconvenience to say the least.

I downloaded the latest build and tried: still crashed.

If you did manage to get past it, would you perhaps be able to share the save file with us? Maybe we can try our luck playing past that point with your save.

**Comment by Rutjan666** [comment]
> > If you did manage to get past it, would you perhaps be able to share the save file with us? Maybe we can try our luck playing past that point with your save.

Oh that's a smart idea!

**Comment by reikohinomoto** [comment]
> Are you 100% sure you got past the right point? If you did manage to get past it, would you perhaps be able to share the save file with us? Maybe we can try our luck playing past that point with your save.

Yes, I'm quite sure. From what I see the crash was happening right after you entered the vault in the building, which was what was happening to me. I inserted the slides in the projector and the game crashed constantly. After trying it again with the latest build, I managed to get past that point and reach the Otherworld, but I'm sorry to say the game now crashes while trying to enter a clock-like room. Here's my save. You can try it yourself, maybe it won't crash and you'll get back to us with some great news.
[4B4E0823.zip](https://github.com/xenia-project/game-compatibility/files/8169926/4B4E0823.zip)

**Comment by Rutjan666** [comment]
> From what I see the crash was happening right after you entered the vault in the building

Actually, you're not supposed to be able to enter the vault with three roman dials right after accessing the 2nd floor of the library.

The solution to the dial puzzle of the vault requires the video projector in room 207 which is accessible at this point.

But the slides required for the projector are in room 200, which is at the top right corner of the map:
[silent-hill-downpour-mysteres-centennial-building-008](https://user-images.githubusercontent.com/33540651/156394662-80d059c2-bc2d-4a5a-bd7b-0a8fce1bcd60.jpg)

But to get there, you need to go through Room 208 (the one with a fixed camera angle) that leads to the hall in the center of the map with an elevator.

I attempted to "bypass" the normal progress of the game by entering the vault first (had to find the combination of the three dials online...), let the cutscene play, but the game still crashes at the same time after room 208.

I suppose there is no other way to access the north part of the map, but I'll try the save file.

**Comment by reikohinomoto** [comment]
> Actually, you're not supposed to be able to enter the vault with three roman dials right after accessing the 2nd floor of the library.
> 
> The solution to the dial puzzle of the vault requires the video projector in room 207 which is accessible at this point.
> 
> But the slides required for the projector are in room 200, which is at the top right corner of the map: [silent-hill-downpour-mysteres-centennial-building-008](https://user-images.githubusercontent.com/33540651/156394662-80d059c2-bc2d-4a5a-bd7b-0a8fce1bcd60.jpg)
> 
> But to get there, you need to go through Room 208 (the one with a fixed camera angle) that leads to the hall in the center of the map with an elevator.
> 
> I attempted to "bypass" the normal progress of the game by entering the vault first (had to find the combination of the three dials online...), let the cutscene play, but the game still crashes at the same time after room 208.

I'm pretty sure I did things in order. I'm not very good with the map in this SH, but I went through a lot of rooms looking for the slides, and none of them crashed. I got them eventually, which according to you are in room 200, but the game crashed as soon as I inserted the slides in the projector. I couldn't get past that point.

After seeing Xenia got a major update I tried it again. It worked. And it seemed that was where people were getting crashes. I made minor progress before it crashed again but it seemed playable. And here we are. Do try the save and get back to us. Hopefully we can all finish this game as a big collaborative effort.

**Comment by Chloroshi** [comment]
Just to be clear, the crash that reikohinomoto had been experiencing in previous builds of the emulator is not the same one that is originally discussed in this thread, which is the crash while saving going from room 208 to the main hall. According to what reikohinomoto said, his crash was when inserting the slides in the projector instead, and I'm not sure that would be a save point (I would suppose not).

I tried reikohinomoto's save and there's definitely progress past that point of the crash. Our game completion is at 25%, while his (I'm gonna go ahead and assume we are all dudes here) got progress up to 37%. However if someone is intending to skip as little gameplay as possible, there's no need to hit "continue" in the game with his save, since there's also previous save points with less game completion. The earliest one post-crash would be at 31%. When loading this save and going from room 208 to the main hall, the game does not crash, but that's probably because there's no saving taking place.

I also tried his save at 25% pre-crash, and I still crash even with his file.

I guess being able to skip the crash and play from 31% till the end is better than nothing at all, however I might sit this one out, sadly. The thing is that his game is on easy difficulty for both puzzle and game difficulty, plus his playthrough and mine are quite different in terms of quests completed. I don't know. It feels like a very broken experience. But still thank you reikohinomoto for your save file.

Long ago I spoke on discord with a new recruit on the Xenia dev team who was willing to look into this crash. I had given him my save file but he never really got back to me. I don't think he ever got around to checking this game.

I think that to fix this crash we need to get the attention of the devs. It's probably fixable if the people with the right skillset dedicate some time to it. So maybe why don't we all message them asking to take another look at this game? It's still frigging Silent Hill we are talking about, come on ;)

**Comment by TAMPIM** [comment]
> Just to be clear, the crash that reikohinomoto had been experiencing in previous builds of the emulator is not the same one that is originally discussed in this thread, which is the crash while saving going from room 208 to the main hall. According to what reikohinomoto said, his crash was when inserting the slides in the projector instead, and I'm not sure that would be a save point (I would suppose not).
> 
> I tried reikohinomoto's save and there's definitely progress past that point of the crash. Our game completion is at 25%, while his (I'm gonna go ahead and assume we are all dudes here) got progress up to 37%. However if someone is intending to skip as little gameplay as possible, there's no need to hit "continue" in the game with his save, since there's also previous save points with less game completion. The earliest one post-crash would be at 31%. When loading this save and going from room 208 to the main hall, the game does not crash, but that's probably because there's no saving taking place.
> 
> I also tried his save at 25% pre-crash, and I still crash even with his file.
> 
> I guess being able to skip the crash and play from 31% till the end is better than nothing at all, however I might sit this one out, sadly. The thing is that his game is on easy difficulty for both puzzle and game difficulty, plus his playthrough and mine are quite different in terms of quests completed. I don't know. It feels like a very broken experience. But still thank you reikohinomoto for your save file.
> 
> Long ago I spoke on discord with a new recruit on the Xenia dev team who was willing to look into this crash. I had given him my save file but he never really got back to me. I don't think he ever got around to checking this game.
> 
> I think that to fix this crash we need to get the attention of the devs. It's probably fixable if the people with the right skillset dedicate some time to it. So maybe why don't we all message them asking to take another look at this game? It's still frigging Silent Hill we are talking about, come on ;)

Yeah, for me was insert the slide in the projector , i never had check the log error when the crash happens , what is it ? for fix this we need to shout to dev

**Comment by Rutjan666** [comment]
> Further discussion belongs on the [Discord server](https://discord.gg/Q9mxZf9). This tracker is only for compatibility reports.

Is there a dedicated thread?

**Comment by Jervan13** [comment]
![image](https://user-images.githubusercontent.com/12176318/160507509-f87e89d1-f33c-4ac5-b937-f7f03ee9dd8b.png)

Hello I'm using Xenia master@0f3207d01 Mar 28 2022 [4B4E0823 v3.0] Silent Hill Downpour <Directx12 - RTV/DSV> I have this wireframe in all cutscenes on some models.

**Comment by angryrat429** [comment]
I managed to get to the orphanage using xenia-canary 91567c531 and i tweaked the following settings in the config file:
license_mask = 1
use_haswell_instructions = true
gpu_allow_invalid_fetch_constants = true
draw_resolution_scale_x = 1
draw_resolution_scale_y = 1
render_target_path_d3d12 = "" 
Vsync = false
vsync_interval = 16 
apply_patches = true

i think i will be able to finish it, i'll keep you posted.
![image](https://user-images.githubusercontent.com/108628447/177052486-903e428d-5fa8-4b91-b1f0-b65534edd9a5.png)

**Comment by angryrat429** [comment]
Main story playable from start to finish( i haven't done all the side quests ) using xenia-canary 91567c531 and the following settings :
license_mask = 1
use_haswell_instructions = true
gpu_allow_invalid_fetch_constants = true
draw_resolution_scale_x = 1
draw_resolution_scale_y = 1
render_target_path_d3d12 = ""
Vsync = false
vsync_interval = 16
apply_patches = true
![image](https://user-images.githubusercontent.com/108628447/177059618-2fb5613d-01a0-4857-a944-fc0fd2ef43f5.png)

**Comment by asolato** [comment]
By using resent Xenia Canary v1.0.2757-master and Game Patches I was able to continue pass projector saving point!
I've played game till 18th floor and the next save point before lighting up a fire works too.

**Comment by LucasJackrabbit** [comment]
(Xenia Canary@84571f8fe Feb 17 2023 - [4B4E0823 v3.0] Silent Hill Downpour <Directx12 - RTV/DSV> )
Played from beginning to end without problems. Slight hiccup at one point with infinite loading screen, but resolved by restarting last checkpoint.
Visual bug with wireframe on most characters during cutscenes still present along with foliage slight visual bug.

**Comment by BeverlyHillsCop** [comment]
**Infinite Loading Screen**
At the 69% completion of the game right after the boss battle at the shore the game gets stuck in an endless loading screen. I've tried using previous checkpoints and coming back to the same point but it keeps repeating. I've read on the forums that this issue was happening with the OG Hardware as well and they got around this issue by moving their save files to a usb stick and playing like that. How can I get around this with canary? Can it be patched?

**Comment by X0Reactor** [comment]
The garbage text on loading screens can be fixed by setting d3d12_readback_memexport to true. Now if the player icon on the map would stop randomly disappearing.

**Comment by M4l1r1s** [comment]
> The garbage text on loading screens can be fixed by setting d3d12_readback_memexport to true. Now if the player icon on the map would stop randomly disappearing.

Hi, just wondering, do the player icon problem still exist? Is there any fix for this?

**Comment by M4l1r1s** [comment]
I played Silent Hill Downpour using Xenia Canary 2fc8c116, everything runs fine except got these two bugs :

1. Player Icon on the map randomly disappear. Sometimes it reappear by itself. It's pretty annoying cannot locate Murphy position on the map, when you really need it:
![map bug](https://github.com/user-attachments/assets/7a8399a4-3e27-44be-be2d-e2823cbcf4bf)

2. Saving Icon won't be gone. Started got this bug when reaching the Mines Area. Now it always there in top right corner:
![save icon bug](https://github.com/user-attachments/assets/27230c5c-a60b-4ef8-b174-a6693799d547)

Is there any setting on Xenia to fix all these? I just wanted to beat the game once (hopefully without these two bugs).
Any helps and advices would be much appreciated. Thank you. :)

**Comment by Margen67** [comment]
> I played Silent Hill Downpour using Xenia Canary 2fc8c116, everything runs fine but got these two bugs :
> 
>     1. Player Icon on the map randomly disappear. Sometimes it reappear by itself. It's pretty annoying cannot locate Murphy position on the map, when you really need it:
>        ![map bug](https://private-user-images.githubusercontent.com/183259460/373849174-7a8399a4-3e27-44be-be2d-e2823cbcf4bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzA2OTksIm5iZiI6MTcyODEzMDM5OSwicGF0aCI6Ii8xODMyNTk0NjAvMzczODQ5MTc0LTdhODM5OWE0LTNlMjctNDRiZS1iZTJkLWUyODIzY2JjZjRiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMjEzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDFlNGFiZTNhNzA4YjdjYmE5MzBkMzM0N2QxMjg4N2E5OWRiYjY4NTQzNmI1Mzg0ODI3MTNjYmJlYjRjZGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hI82wjCrlDoDbNCu6YXnD5FfngJRlCG2fMJXDZuD-0I)
> 
>     2. Saving Icon won't go away. Started got this bug when reaching the Mines Area. Now it always there in top right corner:
>        ![save icon bug](https://private-user-images.githubusercontent.com/183259460/373849224-27230c5c-a60b-4ef8-b174-a6693799d547.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMzA2OTksIm5iZiI6MTcyODEzMDM5OSwicGF0aCI6Ii8xODMyNTk0NjAvMzczODQ5MjI0LTI3MjMwYzVjLWE2MGItNGVmOC1iMTc0LWE2NjkzNzk5ZDU0Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMjEzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWI3ZDljNTYxZjBjNjRhODI2Mzk5NWYzZWExYmVjMGE4NDAyYTljNTYzYzdiZmRmNmYyNzQ2ZWZjMjZjMTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g7XOwL9-wOPsncqYMPR5OIty1CvaCR9uNOspzgaknqo)
> 
> 
> Is there any setting on Xenia to fix all these? I just wanted to beat the game once (hopefully without these two bugs). Any helps and advices would be much appreciated. Thank you. :)

@M4l1r1s Xenia Canary discussion belongs here: https://github.com/xenia-canary/game-compatibility/issues

**Comment by M0RA3O** [comment]
Hi !
so i need help...
when i press start at the start screen the game freeze for fraction of a second 
and it seems that it has something to do with the start button 
any help?
